### ISSUE TITLE
Discussion: Should we set the default logging format to CRI?

### ISSUE THREAD

**Issue by petewall** [grafana/k8s-monitoring-helm#100]
The [default](https://github.com/grafana/k8s-monitoring-helm/blob/main/charts/k8s-monitoring/values.yaml#L334-L337) logging format is currently set to docker. Kubernetes deprecated the docker runtime in 1.20 in favor of CRI.

Should this stay or should the default be migrated to CRI?

**Comment by rgeyer** [comment]
So... Interestingly, the container runtime is exposed in the discovery labels, which I just learned.

Further, there is an agent module which handles a lot of this magic, including fetching, and passing along the container runtime to inform the processing stage. 🤔 

https://github.com/grafana/agent-modules/blob/main/modules/kubernetes/logs/targets/logs-from-worker.river#L54-L72

**Comment by petewall** [comment]
Ooh, I really like this approach.
