### ISSUE TITLE
The stdlib function env() is deprecated

### ISSUE THREAD

**Issue by bentonam** [grafana/k8s-monitoring-helm#1025]
In the alloy logs the message: 

```
level=warn msg="this stdlib function is deprecated; please refer to the documentation for updated usage and alternatives" controller_path=/ contr │
│ oller_id=pod_logs.feature function=env
``` 

shows up quite frequently.  The `env()` function has been deprecated and is not `sys.env()` https://grafana.com/docs/alloy/latest/reference/stdlib/sys/#sysenv

**Comment by petewall** [comment]
Fixed in https://github.com/grafana/k8s-monitoring-helm/pull/1027
