### ISSUE TITLE
Error: template: k8s-monitoring/templates/grafana-agent-logs-config.yaml:5:45: executing "k8s-monitoring/templates/grafana-agent-logs-config.yaml" at <index .Subcharts "grafana-agent-logs">: error calling index: index of untyped nil

### ISSUE THREAD

**Issue by gkaskonas** [grafana/k8s-monitoring-helm#103]
Cannot install the chart

```
Client Version: v1.25.0
Kustomize Version: v4.5.7
Server Version: v1.24.3+k3s1
```

```
helm upgrade --kube-context default --install grafana-k8s-monitoring grafana/k8s-monitoring \
    --namespace "monitoring" --create-namespace --values - <<EOF
cluster:
  name: "default"

externalServices:
  prometheus:
    host: "https://prometheus-prod-05-gb-south-0.grafana.net"
    basicAuth:
      username: "1097405"
      password: "xxxxx"

metrics:
  cost: {enabled: false}

opencost: {enabled: false}
EOF
Release "grafana-k8s-monitoring" does not exist. Installing it now.
Error: template: k8s-monitoring/templates/grafana-agent-logs-config.yaml:5:45: executing "k8s-monitoring/templates/grafana-agent-logs-config.yaml" at <index .Subcharts "grafana-agent-logs">: error calling index: index of untyped nil
```

**Comment by MarkoTukiainen** [comment]
> that will probably fix it.

It does not. I ran into this same problem and added the code as you suggested, the error just changed to:

`Error: template: k8s-monitoring/templates/grafana-agent-config.yaml:4:45: executing "k8s-monitoring/templates/grafana-agent-config.yaml" at <index .Subcharts "grafana-agent">: error calling index: index of untyped nil`

**Comment by petewall** [comment]
OK, I realized this is because the `.Subcharts` variable (used in `k8s-monitoring/templates/grafana-agent-config.yaml`) was introduced in Helm 3.7. Try with a newer version of Helm and see if that makes it work.

**Comment by petewall** [comment]
Closing this. Please try with a newer version of Helm and if the issue still persists, let me know!
