### ISSUE TITLE
Error when traces port is closed

### ISSUE THREAD

**Issue by VictorColome** [grafana/k8s-monitoring-helm#123]
The message error that should appear when the traces port (4317) is closed is not being shown properly.
It is crashing with this error `Error: parse error at (k8s-monitoring/templates/_helpers.tpl:11): unclosed action` instead of the intended print here charts/k8s-monitoring/templates/_helpers.tpl.

I am using Grafana Cloud UI to configure the agents to monitor an AKS cluster.

**Comment by petewall** [comment]
Hmm.. What version of helm are you running (i.e. `helm version`)? I wonder if it doesn't like the multi line error string.

Can you share the command you were running to generate that error message?

**Comment by VictorColome** [comment]
Indeed it was the Helm version. I was using v3.5.0, today updated to latest (3.12.3) and worked. Don't know if helm older versions doesn't like the multi line string... 
Thank you!

**Comment by petewall** [comment]
Great! Glad to hear than an upgrade to helm fixed the issue!
