### ISSUE TITLE
Usage of Grafana Agent-Modules repository

### ISSUE THREAD

**Issue by nlamirault** [grafana/k8s-monitoring-helm#126]
There is a repository [agent-modules](https://github.com/grafana/agent-modules) which defines some modules which can be loaded as a component.
Do you think it could be possible to use these modules or not ?

**Comment by petewall** [comment]
Yeah, it should totally be possible to load modules.
I'm going to piggyback on this issue as a way to create some working examples of loading modules with the chart.

**Comment by petewall** [comment]
I am looking into this, but it'll be for a future iteration of the Helm chart.
