### ISSUE TITLE
cluster label is overloaded

### ISSUE THREAD

**Issue by jack1902** [grafana/k8s-monitoring-helm#130]
Depending on the dashboard context, `cluster` is overloaded.

Whilst `cluster` might be assumed to mean "what kubernetes cluster" should this dashboard filter on, it doesn't always mean that in the context of certain dashboards / integrations provided by grafana-cloud. A good example of this is the `kafka` integration which creates many dashboards. For the Kafka Overview dashboard a filter exists called `cluster` but this doesn't mean "what kubernetes cluster", it means "what kafka cluster". This presents a problem because even though i am scraping my metrics via the relevant `podMonitor` in my environment, the `cluster` is being mapped to what i passed into the `k8s-monitoring` chart under `cluster.name` (which means kubernetes cluster to the k8s-monitoring chart).

Only things i can think of are:
- rename `cluster` to be context aware such as `k8s-cluster` or `kafka-cluster`

I really like this chart as it wires in the bits needed to empower the `grafana-agent`, whilst still using `podMonitor` or `serviceMonitor` (something many charts from bitnami have "out the box"). 

I'm currently working out different options to enable me to pick and choose whether i use `grafana-agent flow` or `podMonitor/serviceMonitor` (i do like the composability provided by the `*Monitor`' since they have `relabellings` etc on them which means charts can have their own configuration for their own dashboards rather than having all the things around monitoring stored centrally

**Comment by skl** [comment]
@jack1902 thanks for raising this, so I can make sure that I understand correctly, you're using Kafka in Kubernetes with both Kubernetes Monitoring and the Kafka integration enabled in Grafana Cloud - then the cluster variable dropdown of the Kafka dashboards is showing a list of Kubernetes clusters instead of Kafka clusters?

**Comment by skl** [comment]
@jack1902 would you mind raising a support ticket for this via your Grafana Cloud account, indicating which stacks are affected and whether it's ok for us to access them? You can reference this Github issue for additional context and I'll let the support team know as well.

**Comment by skl** [comment]
@jack1902 Kafka integration was just updated with Kubernetes support, with an additional kafka_cluster variable to avoid the overloading. You should be able to see it in the integration tab 🙂
