### ISSUE TITLE
Unable to remove labels

### ISSUE THREAD

**Issue by RobCannon** [grafana/k8s-monitoring-helm#133]
I am trying to remove the `uuid` label from our metrics.  It shows up as #1 in the High Cardinality report and I don't see the value in having it since it is a unique value and has no value in filtering.

I am using version 0.2.2 of the helm chart.

This is the configuration I am using.  I am adding the "foo/barx" label so I can validate that the new rules are being processed.
```
        metrics:
          extraRelabelingRules: |-
            rule {
              action = "replace"
              replacement = "bar9"
              target_label = "foo"
            }
            rule {
              action = "labeldrop"
              regex  = "uid"
            }
```
The metrics I see are like this:
```
kube_pod_status_phase {
  cluster="cloud-sandbox",
  foo="bar9",
  instance="k8s-monitoring-kube-state-metrics.monitoring.svc:8080",
  job="integrations/kubernetes/kube-state-metrics",
  namespace="argo-cd",
  phase="Failed",
  pod="argo-cd-argocd-application-controller-0",
  uid="60555d25-21d5-413a-a32c-91eb20622c7c"
}
```

**Comment by RobCannon** [comment]
That worked!  Thank you.

**Comment by petewall** [comment]
Yay! Glad that helped. I'll make an issue to better clarify the difference between `extraRelabelingRules` and `extraMetricRelabelingRules` in the values file and/or docs.
