### ISSUE TITLE
Option to enable control plane metrics and traces

### ISSUE THREAD

**Issue by ThisIsQasim** [grafana/k8s-monitoring-helm#148]
I have a few clusters that were setup with kubeadm via kubespray that I would like to monitor with the Grafana agent but noticed that the metrics and traces for control plane components are missing. Would be great if those could be enabled.

**Comment by petewall** [comment]
I started working on some of this.
This PR adds metrics from the API server and from etcd: https://github.com/grafana/k8s-monitoring-helm/pull/153

**Comment by petewall** [comment]
API server metrics are in. I'll be adding configs for other modules as well, soon.
Which components are you specifically looking for?

**Comment by ThisIsQasim** [comment]
> API server metrics are in. I'll be adding configs for other modules as well, soon. 

Thanks a ton!
> Which components are you specifically looking for?

Scheduler, controller manager, perhaps CoreDNS

**Comment by petewall** [comment]
With the latest change, we've got:
* API Server
* Kube Controller Manager
* Kube Proxy
* Kube Scheduler

For CoreDNS and Etcd, I'm working on something that should enable those, too.

**Comment by ThisIsQasim** [comment]
That’s amazing! I’ll try these out
