### ISSUE TITLE
Windows Exporter (question)

### ISSUE THREAD

**Issue by ChrisMcKee** [grafana/k8s-monitoring-helm#163]
Hi,
   I'm trying to filter windows metrics by deployment but...

The metrics are pumped out looking like from the windows node exporter

```
windows_container_memory_usage_commit_bytes{container_id="containerd://d1659a76157b935dc622bacb390f89f85a602a0ab9508a0f98be23b71798fcf9"} 42.15625
```

The prometheus side looks like 

```
windows_container_memory_usage_commit_bytes{cluster="dev-cluster", instance="ip-10-1-1-1.eu-west-2.compute.internal", job="integrations/kubernetes/windows-exporter", container_id="containerd://d1659a76157b935dc622bacb390f89f85a602a0ab9508a0f98be23b71798fcf9"}
```

I assume the job is suffering from the "exported_" prefix hiding the job; I can't actually tell properly as I'm using grafana cloud. Locally I'd add honor_labels to the prometheus write to retain the export_job as job rather than getting "windows exporter" but I'm not 100% with this chart if that will actually be read when set under metrics.. 
The k8 api shows the containerid etc under statuses (along with name etc) so I assume its possible. But the rewrites dont seem to populate that info and I'm not 100% how to remap in this version vs the standard prometheus deployment. 

Thanks

**Comment by petewall** [comment]
Hello! Help me to understand the concern a bit better.
The first metric only has a `container_id` label
The second metric has the `container_id`, but also has `cluster`, `instance`, and `job`, which are added by the Grafana Agent that scraped the metrics.

Is there something missing? Was there a job label that you expected that got overwritten?

**Comment by ChrisMcKee** [comment]
I was expecting (rightly or wrongly) for Prometheus to map the container to the kubelet info (deployment/namespace/pod name etc) so the event would be augmented with the rest of the information giving a closer match to the data available on the Linux side.

**Comment by petewall** [comment]
Ah sure. In general, from my experience, most metrics don't do a lot of cross-labeling. The reason is that it can make cardinality explode pretty quickly.

If you want to correlate the container ID with pods or other resources, look for other metrics like `kube_pod_container_info` from kube-state-metrics (also scraped by this chart), that'll let you join them.
