### ISSUE TITLE
A bit more flexibility for defining custom river rules would be helpful

### ISSUE THREAD

**Issue by bytheway** [grafana/k8s-monitoring-helm#167]
We're giving the this chart a try to quickly spin up the monitoring for our k8s clusters, but also are self-hosting mimir and would like this grafana agent to be configured to pass along mimir rules (prometheusRule) that helm chart defines, but we can't find any easy way to inject the [mimir.rules.kubernetes](https://grafana.com/docs/agent/latest/flow/reference/components/mimir.rules.kubernetes/) section we need to enable that feature.

If we could have some extraConfig style hooks, like the grafana-agent chart, then we could include that extra rule much more easily.

**Comment by petewall** [comment]
Are you looking for assistance with adding that component? Or are you looking for that component to be added as an option in the chart and values file?

If the first, you could do something like:
```yaml
extraConfig: |
  mimir.rules.kubernetes "rules" {
    address = nonsensitive(local.file.prometheus_host.content)
    basic_auth {
      username = local.file.prometheus_username.content
      password = local.file.prometheus_password.content
    }
  }
```

I haven't used mimir.rules.kubernetes, so you may need to experiment with it a bit.

**Comment by bytheway** [comment]
thanks, I think you are right, I missed the extraConfig option to do this.
