### ISSUE TITLE
Questions about migration from the grafana agent operator 

### ISSUE THREAD

**Issue by Lp-Francois** [grafana/k8s-monitoring-helm#185]
Hey 👋 

I was previously monitoring clusters with grafana agent operator + custom resources such as GrafanaAgent, PodLogs, etc.

I believe the static agent configuration was the default: https://grafana.com/docs/grafana-cloud/monitor-infrastructure/kubernetes-monitoring/configuration/upgrade-k8s/#upgrade-from-static-agent-configuration

As this new helm chart doesn't package the operator, I was wondering how can I migrate my configuration? It raises 3 points, maybe you have the answer to one of them 😅 

1. I used to deploy a `MetricsInstance` with the following settings: `serviceMonitorNamespaceSelector`, `serviceMonitorSelector`, `probeNamespaceSelector`, `probeSelector`. Where can I set the same with this helm chart? (in order to get metrics out of ServiceMonitor deployed along my applications)
  edit: [updated with this comment](https://github.com/grafana/k8s-monitoring-helm/issues/185#issuecomment-1769303001)

2. Where to add `.PodLogs.spec.relabelings`? I used to deployed a PodLogs containing a labeldrop action with a regexp. Can I do it from the helm chart or should I still deploy some custom resources from my side?

3. As it deploys prometheus CRDs, such as `PrometheusRule`, is there a way to configure the managed alertmanager sitting in grafana cloud to pick up alerts deployed in the cluster?

Thanks a lot :)

**Comment by Lp-Francois** [comment]
About `1.`, I noticed the configmap mounted on the grafana agent, and containing the configuration .river has servicemonitor & probes components:

```hcl
// Prometheus Operator ServiceMonitor objects
prometheus.operator.servicemonitors "service_monitors" {
  namespaces = []
  forward_to = [prometheus.relabel.servicemonitors.receiver]
  clustering {
    enabled = true
  }
}

// Prometheus Operator Probe objects
prometheus.operator.probes "probes" {
  namespaces = []
  forward_to = [prometheus.relabel.probes.receiver]
  clustering {
    enabled = true
  }
}
```

I am still not sure how one could update the values of the already existing?

Append is explained here: https://github.com/grafana/k8s-monitoring-helm/blob/main/charts/k8s-monitoring/values.yaml#L433 but I am unsure on how to update an existing block, let's say you want to only select a handful of namespaces.

**Comment by petewall** [comment]
Hello! These are great questions. In general, we should be able to easily do everything in the Helm chart (using Grafana Agent in Flow mode) that you did before with the Operator and associated CRDs.

The [default deployment](https://github.com/grafana/k8s-monitoring-helm/tree/main/examples/default-values) will do the following:
* Deploy...
  * Grafana Agent (actually, two of them)
  * Kube State Metrics
  * Node Exporter
  * OpenCost
* Configure the agent to scrape metrics from: Kube State Metrics, cAdvisor, Kubelet, Node Exporter, OpenCost
* Configure the agent to gather pod logs
* Configure the agent to gather cluster events as logs
* Send all metrics to prometheus (or mimir, Grafana Cloud metrics, etc...)
* Send all logs and cluster events to Loki

That should cover the MetricsInstance, and by default, it looks for ServiceMonitors, PodMonitors, and Probes in all namespaces. By default, it will scrape those for all metrics. If you want to filter down to a certain set (which is what the allowList for the other pre-defined metric sources does, you can specify your own using the `extraMetricRelabelingRules`. I can help if that's what you're looking for.

To set pod log relabelings, you have two options. If its about filtering down to a specific set of pods, you can use:
```
logs:
  pod_logs:
    namespaces: []
      OR
    extraRelabelingRules: ""
```
If you want to add extra log processing stages, you can use this:
```
logs:
  pod_logs:
    extraStageBlocks: ""
```
See the links to the documentation for examples on how to define them in the Flow components.

For your last point about PrometheusRule objects. The chart doesn't handle those directly (yet), but you could probably add support for that with the [mimir.rules.kubernetes](https://grafana.com/docs/agent/next/flow/reference/components/mimir.rules.kubernetes/) component:

```yaml
extraConfig: |
  mimir.rules.kubernetes "rules" {
    address = "GRAFANA_CLOUD_METRICS_URL"
    basic_auth {
        username = "GRAFANA_CLOUD_USER"
        password = "GRAFANA_CLOUD_API_KEY"
    }
  }
```

**Comment by Lp-Francois** [comment]
Hey @petewall, thanks for your detailed answer :) 

I just installed a fresh install after some issues highlighted [here](https://github.com/grafana/k8s-monitoring-helm/issues/234) ^^

Logs & metrics are coming up to my grafana cloud :D 
I just noticed a small change, like the `probe_success` metric exported from the blackbox exporter doesn't have the `namespace` label anymore 🤔 Any idea of what could have changed?

## Relabel, drop metrics

extraRelabelingRules was exactly what I was looking for! And I need to tell I love the allowList to comment out metrics with high cardinality that I don't use a lot (looking at you container_network.* and container_fs.*).
Thanks a lot!

For reference, if anyone ends up in this thread, that's how I pass a rule to the option:

```yaml
...
        metrics: 
          extraRelabelingRules: | 
            rule {
              source_labels = [ "__name__" ]
              action        = "drop"
              regex         = "erlang_vm_.*"
            }
```

## PrometheusRule

This is amazing! That would allow to ship Alerts directly with micro-service and ship them to remote mimir (grafana cloud) 😍 I will give it a try next week for sure!
