### ISSUE TITLE
Issues with sending traces to helm installed tempo behind aws load balancer

### ISSUE THREAD

**Issue by bytheway** [grafana/k8s-monitoring-helm#195]
We've been using this helm chart (thanks, it is awesome!) to quickly get set up sending the right metrics into a self-hosted mimir and tempo stack.  We're running tempo behind an aws load balancer and were having issues getting the trace exporter to work, we kept getting errors with missing headers from alb that prevented grafana agent from sending the traces to tempo.

We modified a forked version of the helm chart and changed the exporter from `otelcol.exporter.otlp` to `otelcol.exporter.otlphttp` and that fixed out issues immediately.

I started looking at maybe making a PR to make this configurable in the helm chart by detecting whether the tempo endpoint was http or host:port style, like

```
{{- define "otlp_traing_endpoint_type" -}}
{{- if hasPrefix "http" .Values.tempo.host }}otlphttp{{- else -}}otlp{{- end -}}
{{- end }}
```
and then updating the river files to use:
```
otelcol.exporter.{{- otlp_tracing_endpoint_type -}}
```

But I noticed the test examples are using  `host: https://tempo.example.com`.

The [documentation](https://grafana.com/docs/agent/latest/flow/reference/components/otelcol.exporter.otlp/) for otelcol.exporter.otlp shows the `HOST:PORT` form that I thought was required, so now I'm not sure if my approach would be accepted.  

Maybe grafana cloud's version of tempo better handles otlp with http URLs?  For me adding http:// prefixes to the otlp exporter resulted in a parsing error when grafana agent started up.

Would a change like the above be acceptable? Detecting the http prefix and switching the exporter to use otlphttp instead?

**Comment by petewall** [comment]
Thanks for opening this issue!
Yeah, I wouldn't be surprised if the examples aren't exactly correct. We'll get a fix for that.
So, a few options:
1. Automatically detect based on url
2. Be explicit

The first would require no changes to the values file, but would conditionally use `otelcol.exporter.otlp` or `otelcol.exporter.otlphttp` based on the format of the URL.

The second would include a:

```
externalServices:
  tempo:
    host: https://tempo.example.com
    protocol: otelhttp
```

That would leave room for other protocols in the future that might or might-not use `http://` as a prefix.

**Comment by petewall** [comment]
Take a look at this PR: https://github.com/grafana/k8s-monitoring-helm/pull/226
This will allow you to set `protocol: otlphttp` on the tempo definition.
