### ISSUE TITLE
If the cluster label is already set, we don't overwrite it

### ISSUE THREAD

**Issue by petewall** [grafana/k8s-monitoring-helm#202]
We're setting the cluster variable with the `external_labels` section of [`prometheus.remote_write`](https://grafana.com/docs/agent/latest/flow/reference/components/prometheus.remote_write/#arguments). That appears to insert the label, but it does not upsert it.

**Comment by rknightion** [comment]
One thing worth mentioning here is that some users may have dependencies on the "broken" method. For example, elasticsearch, kafka and zookeeper community charts set the "cluster" label which folk then select in their dashboards. 

In our estate we set a unique "k8s-cluster" label to identify clusters given how "cluster" can mean different things to many people. Might be worth covering that in docs somewhere.

**Comment by petewall** [comment]
Fair point! I'll close this issue as a "known quirk".
We wont overwrite the cluster label.
