### ISSUE TITLE
Logs: for agent daemonset, limit Kubernetes discovery to only pods on the same node

### ISSUE THREAD

**Issue by yafanasiev** [grafana/k8s-monitoring-helm#210]
Hi!

We are using this chart to collect both metrics and logs, having agent deployment collect metrics and agent daemonset collecting logs and sending them to Loki. It works great on smaller clusters, but on bigger ones (4000+ pods) we see very high memory usage (up to 1Gi of memory on a single daemonset pod). I believe this is caused by each agent  pod querying all of the pods from Kubernetes API, performing relabeling and only then narrowing down pod selection during `local.file_match` stage. Official agent documentation has this example to limit discovery to only pods running on the same node:

```river
discovery.kubernetes "k8s_pods" {
  role = "pod"
  selectors {
    role = "pod"
    field = "spec.nodeName=" + constants.hostname
  }
}
```

This looks like something that could be added as a default to the chart to improve resource consumption on the agent daemonset. Moreover, If we could also allow custom selectors to be passed through values, that would also be a great addition to replicate functionality that is present in other log collectors. For example, Fluentbit can skip collecting logs from a pod based on a special annotation. We are currently replicating this behaviour by adding the following relabeling rule

```river
  rule {
    source_labels = ["__meta_kubernetes_pod_annotation_fluentbit_io_exclude"]
    regex = "true"
    action = "drop"
  }
```

but doing this during Kubernetes discovery stage would improve performance even further.

**Comment by petewall** [comment]
These are great suggestions. Let me take a look and see what we can do.

**Comment by yafanasiev** [comment]
@petewall after a week of testing, I can confirm that logs agent is now consuming ~100MiB memory even on the biggest cluster. Great work!

**Comment by petewall** [comment]
Thank you so much for following up on this! I'm glad things are working better now.
