### ISSUE TITLE
Invalid port name "otlp-traces-http" on Azure AKS

### ISSUE THREAD

**Issue by abustany** [grafana/k8s-monitoring-helm#220]
When attempting to deploy this chart on Azure AKS, the `grafana-k8s-monitoring-grafana-agent` stateful set fails to deploy with the following error:
```
Pod "grafana-k8s-monitoring-grafana-agent-0" is invalid: spec.containers[0].ports[2].name: Invalid value: "otlp-traces-http": must be no more than 15 characters
```

I don't know if this is AKS specific (Azure has lots of random limits all over the place so I wouldn't be surprised).

As a workaround, I edited the stateful set manifest to rename the port to `otlp-traces-h`.

Additional info:
```
$ helm ls
NAME                  	NAMESPACE	REVISION	UPDATED                                	STATUS  	CHART                	APP VERSION
grafana-k8s-monitoring	grafana  	3       	2023-10-27 14:54:34.15259691 +0200 CEST	deployed	k8s-monitoring-0.2.12	1.3.2
```

**Comment by petewall** [comment]
Yeah, we had an issue earlier with the port name in the examples. As you saw, you can shorten the name. We [currently recommend](https://github.com/grafana/k8s-monitoring-helm/blob/main/examples/traces-enabled/values.yaml#L31) `otlp-http`.

**Comment by abustany** [comment]
oh right I hadn't realized the port name comes from my `values.yaml` :facepalm: Thanks for the hint, we can close the issue then.

**Comment by petewall** [comment]
All good! Happy to help.
