### ISSUE TITLE
[FEATURE] Add nodeSelector and tolerations to validation webhook

### ISSUE THREAD

**Issue by yafanasiev** [grafana/k8s-monitoring-helm#241]
Currently, validation hook only has nodeSelector to be scheduled on Linux nodes (https://github.com/grafana/k8s-monitoring-helm/blob/16a7642a565d2dbb361f2492bf8fd2b243362036/charts/k8s-monitoring/templates/hooks/validate-configuration.yaml#L35). However, in clusters where all nodes have specific labels and taints validation pod has nowhere to be scheduled and currently it is not possible to specify those through the chart.

If this is something maintainers are interested in, I could help with the PR.

**Comment by petewall** [comment]
This is a great idea, and we should extend it to the test job as well (the one that runs with `helm test`).
I'd totally welcome a PR.

We don't have a section for the validator in the values file yet. Maybe something like this:
```diff
+ validator:
+  nodeSelector:
+    kubernetes.io/os: linux
+  tolerations: []
+
  # Settings for the test job, runnable by "helm test"
  test:
    # -- Additional queries that will be run with `helm test`.
    # NOTE that this uses the host, username, and password in the externalServices section.
    # The user account must have the ability to run queries.
    # Example:
    # extraQueries:
    #   - query: prometheus_metric{cluster="my-cluster-name"}
    #     type: [promql|logql]
    extraQueries: []

    # -- How many times to attempt the test job
    attempts: 10

    image:
      # -- Test job image registry.
      registry: docker.io
      # -- Test job image repository.
      image: ubuntu
      # -- Test job image tag.
      tag: jammy
      # -- Optional set of image pull secrets.
      pullSecrets: []
  
+  nodeSelector:
+    kubernetes.io/os: linux
+  tolerations: []
```

With some nice comments in the values file, too.

**Comment by petewall** [comment]
Here is the PR: https://github.com/grafana/k8s-monitoring-helm/pull/248
I'd appreciate a 👍🏻 if you think it'll meet your needs!

**Comment by yafanasiev** [comment]
Hey @petewall that looks perfect! Sorry I did not get to it earlier. I will test the new release as soon as available and let you know.

**Comment by petewall** [comment]
0.4.2 is released with this change. Try it out and let me know how it worked!

**Comment by yafanasiev** [comment]
Just tested it - works like a charm. Thanks a lot @petewall!
