### ISSUE TITLE
Add ability to set TLS options for `externalServices.loki`

### ISSUE THREAD

**Issue by julian-waibel** [grafana/k8s-monitoring-helm#247]
According to the [Values documentation](https://github.com/grafana/k8s-monitoring-helm/tree/main/charts/k8s-monitoring#values) it's possible to set TLS options for both Prometheus (via `externalServices.prometheus.tls`) and Tempo (via `externalServices.tempo.tlsOptions`, see #199).

But currently not yet for Loki. It would be great to have a `externalServices.loki.host.tls` field which then get passed to Loki similar to Prometheus and Tempo.

A small note: For Prometheus the field is called `tls` while for Tempo it's called `tlsOptions`. Maybe using the same field name would provide more clarity to users.

Thanks!

**Comment by petewall** [comment]
Dropping this link as a reference for implementation, we'll need to populate these fields:
https://grafana.com/docs/agent/latest/flow/reference/components/loki.write/#tls_config-block
