### ISSUE TITLE
Default `metrics.kube-state-metrics.allowList` Helm value contains duplicates

### ISSUE THREAD

**Issue by julian-waibel** [grafana/k8s-monitoring-helm#256]
Default [`metrics.kube-state-metrics.allowList`](https://github.com/grafana/k8s-monitoring-helm/blob/0015f75d31615b66064577d9ea6a345ae45a7892/charts/k8s-monitoring/values.yaml#L261) Helm value contains duplicates:

https://github.com/grafana/k8s-monitoring-helm/blob/0015f75d31615b66064577d9ea6a345ae45a7892/charts/k8s-monitoring/values.yaml#L273-L274

https://github.com/grafana/k8s-monitoring-helm/blob/0015f75d31615b66064577d9ea6a345ae45a7892/charts/k8s-monitoring/values.yaml#L281-L282

**Comment by petewall** [comment]
Fixed in https://github.com/grafana/k8s-monitoring-helm/commit/0769d6b4e665a1dedc6e2824807c26c272e899bf
