### ISSUE TITLE
Feature Request: Add jaeger receiver value

### ISSUE THREAD

**Issue by skl** [grafana/k8s-monitoring-helm#260]
So far, for traces, oltp and zipkin receivers are referenced in the helm values. Is it worth adding a value that creates a `otelcol.receiver.jaeger` component?

**Comment by bradleypettit** [comment]
I tried enabling one today so definitely worth adding it I think! I see Pete's already begun which is great, I'll keep an eye on this and try it out once done.

There may be a way to do this differently, but I'm trying to configure GEM deployed to the same cluster to send its traces via the k8s-monitoring managed agent. It looks as if GEM/Mimir only support Jaeger at the moment so makes sense we have it as a receiver in this chart.
