### ISSUE TITLE
Unexpected behaviour of `*.allowList: []`

### ISSUE THREAD

**Issue by julian-waibel** [grafana/k8s-monitoring-helm#265]
The [Custom Allow Lists](https://github.com/grafana/k8s-monitoring-helm/tree/main/examples/custom-allow-lists) example page states that setting the allow list value to `[]` results in "No filtering; allow all metrics".

My very personal expectation without reading the docs would be that passing an empty list as allow list would result in "Deny all metrics" behaviour. So this comes unexpected to me and might get wrong by other users as well if this specific nested example page is not read carefully.

Therefore changing the implementation and updating the documentation to the following might be more clear to users and gives the possibility to deny all metrics, e.g. for debugging purposes.

My suggestion:

| Allow List Value                                | Result                                      |
|-------------------------------------------------|---------------------------------------------|
| `[]`                       | Deny all metrics from getting sent to Prometheus             |
| `[".*"]` or `null`                      | No filtering; allow all metrics             |
| `["node_.*"]`                                   | Allow only metrics that start with `node_`  |
| `["kubelet_node_name","kubernetes_build_info"]` | Allow only specific metrics                 |

Current implementation documentation:

https://github.com/grafana/k8s-monitoring-helm/blob/bd6fc4630db100178db342fea2fcaed1c4c815ac/examples/custom-allow-lists/README.md?plain=1#L7-L11

**Comment by petewall** [comment]
Closing, because allowLists are going away in version 0.9
