### ISSUE TITLE
Unable to drop the "filename" label

### ISSUE THREAD

**Issue by jan-osch** [grafana/k8s-monitoring-helm#267]
I've tried  dropping the filename label which has a very high cardinality in my project (running dozens of ephemeral pods per minute)

I have tried multiple different ways but I'm unable to drop the `filename` and `stream` label.

Here is an excerpt from my helm values:
```yml
logs:
  enabled: true
  pod_logs:
    namespaces:
      - company_name
      - default
    extraRelabelingRules: |
      rule {
        regex = "^(pod|job|filename|container|stream)$"
        action = "labeldrop"
      }
      rule {
        regex = "^filename$"
        action = "labeldrop"
      }
      rule {
        source_labels = ["filename"]
        regex = "/.+"
        action = "drop"
      }
``` 

How do I get rid of `filename`

**Comment by skl** [comment]
I've asked Loki team about this but let me know if you resolve it in the mean time.

**Comment by jan-osch** [comment]
I even tried overriding it via the `loki` externalLabels settings, but it didn't work. Thank you for the swift response!

```yml
  loki:
    externalLabels:
      filename: 'be-gone'
```
