### ISSUE TITLE
Add annotations to support TLS

### ISSUE THREAD

**Issue by petewall** [grafana/k8s-monitoring-helm#291]
This one is interesting because it has bigger implications for how scraping works.
It *might* be as easy as setting `__scheme__` to `https`, which could be done with an annotation like `k8s.grafana.com/metrics.scheme`.

However, if it's an https target, we'd need to probably set the TLS cert.

Easy approach would be to set `__scheme__` and see what happens in the `prometheus.scrape` component.

Medium approach would be to set `__scheme__` in the initial `discovery.relabel`, then use two more `discovery.relabel` components to include and exclude https schemes, then use two `prometheus.scrape` components.

**Comment by petewall** [comment]
First step would be to identify a workload that shares metrics via TLS and without other auth (which we wont support initially).

**Comment by skl** [comment]
A few of the control plane components use https (controller manager, scheduler, api server), e.g.:

```
  prometheus.scrape "controllermanager" {
    job_name   = "kube-controller-manager"
    targets    = discovery.relabel.controllermanager.output
    scheme     = "https"
    bearer_token_file = "/var/run/secrets/kubernetes.io/serviceaccount/token"
    tls_config {
      insecure_skip_verify = true
    }
    clustering {
      enabled = true
    }
    forward_to = [prometheus.relabel.controllermanager.receiver]
  }
```

**Comment by skl** [comment]
I can see agent has picked up on the annotations after the following command on the kubeadm-controlplane cluster:

```shell
kubectl -n kube-system annotate pods kube-controller-manager-ip-172-31-16-35 \
  k8s.grafana.com/scrape="true" \
  k8s.grafana.com/job="annotate-controllermanager" \
  k8s.grafana.com/metrics.portNumber="10257" \
  k8s.grafana.com/metrics.scheme="https"
```

Here's what the agent sees on `discovery.relabel.annotation_autodiscovery_pods`:

```
__meta_kubernetes_namespace                                                = "kube-system",
__meta_kubernetes_pod_annotation_k8s_grafana_com_job                       = "annotate-controllermanager",
__meta_kubernetes_pod_annotation_k8s_grafana_com_metrics_portNumber        = "10257",
__meta_kubernetes_pod_annotation_k8s_grafana_com_metrics_scheme            = "https",
__meta_kubernetes_pod_annotation_k8s_grafana_com_scrape                    = "true",
```

Not seeing metrics or any scrape debug info though.

**Comment by petewall** [comment]
The new `helm test` will run a config analysis pod that'll easily print out the discovery and scrape components. You can then see if there were failures in scraping.

**Comment by skl** [comment]
I ran the test but can't find a way to see the output:

```shell
helm test grafana-k8s-monitoring
NAME: grafana-k8s-monitoring
LAST DEPLOYED: Fri Dec 15 18:06:33 2023
NAMESPACE: default
STATUS: deployed
REVISION: 1
TEST SUITE:     test-grafana-k8s-monitoring
Last Started:   Mon Dec 18 13:38:28 2023
Last Completed: Mon Dec 18 13:38:28 2023
Phase:          Succeeded
TEST SUITE:     analyze-grafana-k8s-monitoring
Last Started:   Mon Dec 18 13:38:28 2023
Last Completed: Mon Dec 18 13:38:36 2023
Phase:          Succeeded
TEST SUITE:     test-grafana-k8s-monitoring
Last Started:   Mon Dec 18 13:38:36 2023
Last Completed: Mon Dec 18 13:38:42 2023
Phase:          Succeeded
```
