### ISSUE TITLE
helm install fails [k8s-monitoring/templates/tests/test.yaml]

### ISSUE THREAD

**Issue by Irmius** [grafana/k8s-monitoring-helm#292]
Hello,

Helm install fails, seems like related to a [commit made 2 days ago](https://github.com/grafana/k8s-monitoring-helm/commit/0304fe1cf238300935e7aa2b7758874e7f7a04fc).

```
helm repo add grafana https://grafana.github.io/helm-charts
helm install grafana-k8s-monitoring grafana/k8s-monitoring --create-namespace -n monitor
Error: template: k8s-monitoring/templates/tests/test.yaml:125:58: executing "k8s-monitoring/templates/tests/test.yaml" at <index .Subcharts "grafana-agent">: error calling index: index of untyped nil
```

**Comment by skl** [comment]
@Irmius I've just tested and seems ok for me, what's your `helm version` output? Mine is:

```shell
version.BuildInfo{Version:"v3.13.2", GitCommit:"2a2fb3b98829f1e0be6fb18af2f6599e0f4e8243", GitTreeState:"clean", GoVersion:"go1.21.4"}
```

**Comment by petewall** [comment]
Closing this. Please re-open if you encounter this again!

**Comment by LingamEswar** [comment]
HI Team,
We are also facing the same issue. 
Helm Version : Version:"v3.11.3", GitCommit:"323249351482b3bbfc9f5004f65d400aa70f9ae7", GitTreeState:"clean", GoVersion:"go1.20.3"

Error:  executing "k8s-monitoring/templates/tests/test.yaml" at <index .Subcharts "grafana-agent">: error calling index: index of untyped nil

Any help is much appreciated.

**Comment by petewall** [comment]
I'll answer this in #494
