### ISSUE TITLE
Request: support templates in extraStages

### ISSUE THREAD

**Issue by cydergoth** [grafana/k8s-monitoring-helm#293]
Our agent log filters have become ... complex, and it would be easier for us to manage them if we could break down the river configuration into sub-files and be able to include them via templating with helm Files.Get template directives.

Would it be possible to support a tpl version of extraStages in addition to the non-tpl version?

**Comment by petewall** [comment]
Hey! Interesting idea... I can totally see how things become complex.

Can you give me some more information about what you'd like to see split up into files? Is it the core config that the chart generates, or is it additional custom configs that you are adding?

You can use Helm's `--set-file` flag to set a value using a file, rather than keeping it in the same values file as everything else:
```
helm install k8smon grafana/k8s-monitoring -f my-values.yaml --set-file .logs.pod_logs.extraStageBlocks=logStageBlocks.txt
```

**Comment by cydergoth** [comment]
Hi! Thanks for the quick response!

It is mostly pipelines to rationalize log formats from different legacy
apps into OpenTelemetry JSON log format. So a match, some extraction
filters and some label swabbing then a render back to the log line as JSON.

We also have a lot of noise filters which we would like the developers to
be able to manage themselves, so having them in a separate file would help.

Using a template we could use File.Glob and File.Get to load those separate
files all into the block pipeline.

**Comment by dyurchanka** [comment]
Hey, first of all really appreciate all the work you are doing on this helm chart. 
We are facing the same challenge I guess: extraStageBlocks is a multi line string and we cannot provide/merge multiple files I guess with --set-file. As well as we cannot provide/merge multiple values files with extraStageBlocks. 
Lets imagine scenario when platform team developed default company wide river config for log processing and put in under extraStageBlocks, and also we need some custom user specific configs for separated k8s clusters and we cannot add it using helm now as it will just override the key. We have to copy/paste default config and add custom one for specific clusters. 
Adding `tpl` function as it is done in agent helm chart (https://github.com/grafana/agent/blob/v0.40.0/operations/helm/charts/grafana-agent/templates/configmap.yaml#L11) can provide for us more control on this. What do you think? Thanks

**Comment by petewall** [comment]
FYI, this PR makes it so the `extraStageBlocks` support Helm templates: https://github.com/grafana/k8s-monitoring-helm/pull/427
