### ISSUE TITLE
Question/Request : Dropping specific metrics and labels

### ISSUE THREAD

**Issue by edas-smith** [grafana/k8s-monitoring-helm#308]
Hello,

I am using version 0.7.3 of this helm chart and have come across something that I am a bit confused about / unsure how to approach.

Cardinality ( and the amount of series ) is very important to manage properly in Grafana, as you can rack up a huge bill if you are not careful fairly easily.

I am using the metric "container_memory_working_set_bytes" here as an example.

This metric can have a fairly high series as it has labels such as : 
id
name
pod
image
container

What I wanted to ask, was whether it was possible to say "drop" these labels or a select label such as "name" for example to decrease the amount of series.

Does the approach look something like this? 
```
metrics:
  scrapeInterval: 1m
  extraRelabelingRules: |-
    rule {
      source_labels = ["__name__"]
      regex = "container_memory_working_set_bytes"
      target_label = "name"
      action = "labeldrop"
    }
```
But the above doesn't seem to drop the "name" label?  Any help on this would be appreciated as I am not entirely sure if this is how I should be approaching this.

Furthermore, can I confirm whether this is the "correct" way of dropping metrics completely? ( i.e, stop them from being pushed into Grafana ) :
```
externalServices:
  prometheus:
    hostKey: host
    basicAuth:
      usernameKey: username
      passwordKey: password
    secret:
      create: false
      name: "grafana-prometheus-secret"
    writeRelabelConfigRules: |-
      write_relabel_config {
        source_labels = ["__name__"]
        regex = "metric_1_to_drop|metric_2_to_drop|metric_3_to_drop"
        action = "drop"
      }
```
Any help/further info with the above would be greatly appreciated!

**Comment by petewall** [comment]
From my understanding, with the `labeldrop` action, the `regex` field is matching the label or labels to drop. I'd have to do more research to see how to drop labels from specific metrics, rather than from all metrics, but this might do what you're looking for:
```
metrics:
  cadvisor:
    extraMetricRelabelingRules: |-
      rule {
        regex = "name"
        action = "labeldrop"
      }
```

You'll want to use `extraMetricRelabelingRules` instead of `extraRelabelingRules` because the first applies rules to the metrics scraped, while the second applied rules to the targets discovered (pre-scraping).

**Comment by petewall** [comment]
Your rule for dropping metrics looks correct, too.

**Comment by edas-smith** [comment]
Excellent thank you so much for such a quick response @petewall this seems to be working perfectly now :)! Happy to close this, but yes would be interesting to see if this can be done at a per-metric level though! Do have a nice upcoming Christmas and New Year.
