### ISSUE TITLE
Request: Add dockercontainers mount option to value file under grafana-agent-logs

### ISSUE THREAD

**Issue by BitKickerBHS** [grafana/k8s-monitoring-helm#309]
I was not seeing any pod logs just the error `level=error msg="error getting os stat"` until I added dockercontainers mount option.  Would it be possible to add dockercontainers mount option to the value file? 

```
> grafana-agent-logs:
>   agent:
>     configMap:
>       create: false
>     mounts:
>       varlog: true
>       dockercontainers: true
```

**Comment by petewall** [comment]
Quick question, what kind of Kubernetes cluster are you running?

**Comment by BitKickerBHS** [comment]
Running Rancher RKE, v1.25.13

**Comment by Andrii-Khodyriev** [comment]
I have exactly the same problem

Log example : 
`ts=2023-12-26T20:23:33.462127486Z level=error msg="error getting os stat" component=local.file_match.pod_logs path=/var/log/pods/prod_simulation-assignment-797d7f7d85-hdnfn_ce3f8946-0fe9-44c4-9ffb-7f28b51ce39f/simulation-assignment-service/0.log err="stat /var/log/pods/prod_simulation-assignment-797d7f7d85-hdnfn_ce3f8946-0fe9-44c4-9ffb-7f28b51ce39f/simulation-assignment-service/0.log: no such file or directory"`

Solution: 
Exactly the same as the Author's
added the following: 
`grafana-agent-logs:
  agent:
    configMap: 
      create: false
    mounts:
      varlog: true
      dockercontainers: true
`
