### ISSUE TITLE
Scrape interval option is not applied to prometheus.operator.* components

### ISSUE THREAD

**Issue by SvenKirschbaum** [grafana/k8s-monitoring-helm#313]
Based on the documentation, I would expect the `metrics.scrapeInterval` value introduced in #105  to set the `default_scrape_interval` option for the `prometheus.operator.*` flow components, configuring the scrape interval for these targets, if it has not been specified inside the CRDs. This is however currently not the case, and besides overriding the agent config manually, there exists no way of changing the default value.

**Comment by petewall** [comment]
The metrics.scrapeInterval and the metrics.podMonitors.scrapeInterval should set the default scrape interval, if it's not already set inside the PodMonitor itself. Same for ServiceMonitors and Probes.
Look for it in the next release!
