### ISSUE TITLE
Tighten up validation with values.schema.json

### ISSUE THREAD

**Issue by petewall** [grafana/k8s-monitoring-helm#325]
Improvements to values.schema.json can be added to reduce bad configurations including:

1. field validation
This would prevent misconfiguration for specific fields. It already validates field types, but can it validate that the fields have valid data?

  - Rule blocks should only allow valid [rules](https://grafana.com/docs/alloy/latest/reference/components/discovery.relabel/#rule-block)
  - k8sattributes label and [annotation](https://grafana.com/docs/alloy/latest/reference/components/otelcol.processor.k8sattributes/#annotation-block) blocks should only allow valid values.

2. prevent additional unknown values
Fail if unknown values are accidentally set. This will catch misspelling or just plain wrong fields.
The exception to this will be the dependent charts, which we don't want to control the values for.

3. check for related fields
Similar to the check that clustering is enabled if log gathering uses the K8s API, we should enforce that dependent configurations are set. Maybe that belongs in templates, like the aforementioned check, or maybe it can be encoded in the schema.

**Comment by ajaffie** [comment]
Just stumbled across an issue with the schema that makes `metrics.autoDiscover` relabeling rules unusable:
> - metrics.autoDiscover.extraMetricRelabelingRules: Invalid type. Expected: null, given: string

Seems like these couple lines: https://github.com/grafana/k8s-monitoring-helm/blob/8b813e5d31a993b34192961ad07563363861cfe1/charts/k8s-monitoring/values.schema.json#L528-L533

**Comment by petewall** [comment]
Ah! Thanks for finding that. I just opened #330 to address that.

**Comment by petewall** [comment]
The issue you found should be fixed now!

**Comment by petewall** [comment]
Not changing this for now. The validation will be improved for version 2.0
