### ISSUE TITLE
Make a doc about alternative install instructions

### ISSUE THREAD

**Issue by petewall** [grafana/k8s-monitoring-helm#333]
If users can't or don't want to use Helm to install the chart, how can they do things?
We should make a doc about some alternatives

1. Use `Helm template`
2. Use ArgoCD

**Comment by joejulian** [comment]
Are you going to explain them all? helmfile, fluxcd, etc, etc

There's value in being opinionated. You build and test this and ensure it works and is reliable. Documenting every other way to avoid using helm is expensive, and prone to having unexpected failures unless you build a massive testing matrix for all possibilities.

Just focus on making this method strong, well tested, and reliable. Feel so confident with this tool that you don't just toss it out and replace it again next year.

**Comment by petewall** [comment]
Valid points.
The focus on this doc would not be to cover the breadth of all install options, but to provide guidance around the most popular methods. It'd be a doc where we can also document known issues or requirements found by users who are installing in a certain manner.
