### ISSUE TITLE
Add the ability to deploy Pyroscope

### ISSUE THREAD

**Issue by petewall** [grafana/k8s-monitoring-helm#365]
https://grafana.com/oss/pyroscope/

**Comment by petewall** [comment]
What would this mean:
1. In our test environments, deploy Pyroscope along with Prometheus, Loki, Tempo.
2. Add a "pyroscope" section to "externalServices" in values.yaml
3. Add a "profiles" section to values.yaml
4. Add Grafana Agent code to scrape profiles and deliver them to Pyroscope.
5. Update the query test script to run queries

**Comment by maurizio-vitale** [comment]
> Add Grafana Agent code to scrape profiles and deliver them to Pyroscope.

Does this cover eBPF, which is the most important way we'll collect profiles?
[we'll  also scrape  golang services, but C++ code is very important]

**Comment by simonswine** [comment]
👋 I am working on the Pyroscope team. For collecting eBPF we need to run as a DaemonSet, not too sure how hard this is to achieve with your helm chart.

**Comment by danielloader** [comment]
I noticed the 0.13.x release had pyroscope added, but I can't get it to work with grafana cloud.

```
grafana-agent ts=2024-04-05T16:31:20.090297957Z level=warn msg="final error sending to profiles to endpoint" component=pyroscope.write.profiles_service endpoint=https://tempo-prod-1-prod-eu-west-2.grafana.net:443 err="unauthenticated: authentication error: invalid scope requested"
```

Tried new keys, tried giving the key _all_ scopes.
