### ISSUE TITLE
Add the ability to deploy Beyla

### ISSUE THREAD

**Issue by petewall** [grafana/k8s-monitoring-helm#366]
https://grafana.com/oss/beyla-ebpf/

**Comment by JoaoLeao7** [comment]
Hello @petewall ,

I'm using the 1.0.2 version of the k8s monitoring chart, is it possible to deploy Beyla with it or is there a better way to deploy Beyla not using the chart?

Thanks

**Comment by petewall** [comment]
I'm kicking around the process of including it in this chart. For now, the easiest is to deploy it by itself through it's own [Helm chart](https://github.com/grafana/beyla/tree/main/charts/beyla). Then configure it to send the data to the Alloy instance from this chart.

**Comment by rodrigoccaldas23** [comment]
Hello
Last week we migrated from agent to alloy and when trying to integrate beyla using `beyla.ebpf` we got this error (even with `--stability.level=public-preview`):

![image](https://github.com/grafana/k8s-monitoring-helm/assets/48653110/f0b7a399-0abb-4678-acef-1439b0f0d053)

**Comment by petewall** [comment]
This is done. Closing.
