### ISSUE TITLE
how can i set the metrics_path 

### ISSUE THREAD

**Issue by JangoCG** [grafana/k8s-monitoring-helm#378]
Hi,
Spring Boot provided metrics under  /actuator/prometheus
with the static grafana agent on my local machine I had to set the metrics path like so

 metrics_path: /actuator/prometheus
 
 Is this possible too with this helm chart? How would I do that?
 Best Regards

**Comment by petewall** [comment]
It depends on how you're configuring the chart to scrape the metrics. If you're using extraConfig and you're following a doc like https://github.com/grafana/k8s-monitoring-helm/blob/main/charts/k8s-monitoring/docs/ScrapeApplicationMetrics.md, you can set the `metrics_path` in the [prometheus.scrape](https://grafana.com/docs/agent/latest/flow/reference/components/prometheus.scrape/) component.

If you're using the `k8s.grafana.com/scrape=true` annotation, then you can also set the `k8s.grafana.com/metrics.path=/actuator/promethesus` annotation.

**Comment by JangoCG** [comment]
Thank you pete, I got it to work by using the annotations
