### ISSUE TITLE
PriorityClass

### ISSUE THREAD

**Issue by mmomont** [grafana/k8s-monitoring-helm#430]
Hello

Could we get a support for `PriorityClass`? Either I missed it or it's currently impossible to pass the name of a `PriorityClass`.

Every now and then we end up having in `Pending` state:
- grafana-agent-logs
- prometheus-node-exporter

I'd like to assign `PriorityClass` to these so in case the above happens Kubernetes eviction mechanism kicks in.

**Comment by petewall** [comment]
If you can do it with the dependency Helm charts, you can do it in this chart!

For the [Grafana Agent](https://github.com/grafana/agent/tree/main/operations/helm/charts/grafana-agent) and [Alloy](https://github.com/grafana/alloy/tree/main/operations/helm/charts/alloy) charts, you can set it like this:
https://github.com/grafana/agent/blob/main/operations/helm/charts/grafana-agent/values.yaml#L188-L189

That means, to set it on the `grafana-agent-logs` section, you just put that underneath that section:

```yaml
grafana-agent-logs:
  controller:
    priorityClassName: <string>
```

Similarly, for the [Node Exporter](https://github.com/prometheus-community/helm-charts/blob/main/charts/prometheus-node-exporter/values.yaml#L404-L405) chart, it's just at the top level of their values file. So, to set it in this chart, use this:

```yaml
prometheus-node-exporter:
  priorityClassName: <string>
```
