### ISSUE TITLE
Add ability to specify the whole config in values

### ISSUE THREAD

**Issue by petewall** [grafana/k8s-monitoring-helm#45]
A full values override.

The OTel Collector helm chart wants users to put their whole config in the values:
https://github.com/open-telemetry/opentelemetry-helm-charts/blob/main/charts/opentelemetry-collector/values.yaml#L72-L144

It'd be nice to support the same, which would allow for ease of customization. The risk is that users lose the benefit of getting new recommended config updates.

**Comment by davhdavh** [comment]
What would be the point in installing an opinionated config, just to overwrite it with another config? If people want to that they should just grab all of the dependencies themselves and confgiure from scratch.

**Comment by petewall** [comment]
I'm convinced. At least until I get a compelling reason to bring this idea back.
