### ISSUE TITLE
Swap Agent for Alloy

### ISSUE THREAD

**Issue by petewall** [grafana/k8s-monitoring-helm#454]
[Grafana Alloy](https://github.com/grafana/alloy) has been released and is the successor to the Grafana Agent. We should rebase the Helm chart to use Alloy.

**Comment by scarolan** [comment]
Yes please! From what I can tell it is backwards compatible.  I haven't tested on a k8s cluster yet but a drop-in replace worked fine on an Ubuntu machine.

**Comment by danielloader** [comment]
Oh boy another large change, seen static mode, static operator, flow mode and now alloy.

While I’m super glad alloy has come out I really hope this is the last move for a while!

**Comment by petewall** [comment]
@danielloader I totally get it! I know the updates can be painful. I'm working on this PR with the idea that you'd have to do little or no changes, just a `helm upgrade` will suffice.

Let me know if there are upgrade pains that you've encountered. I'd love to think through ways that might smooth the rough edges!

**Comment by juupas** [comment]
I just changed our "standalone" Grafana Agent reading logs from Azure Event Hubs via config map configuration to Alloy and it was quite smooth ride. In the Helm values file I just changed the `agent` to `alloy` and removed the `mode` config setting.

**Comment by danielloader** [comment]
I know this is somewhat unrelated, but I hope the team who do the frontend work on Grafana Cloud update the helm install (and auto token creation with the correct scopes) to celebrate the 1.0 release shortly after merge.

**Comment by petewall** [comment]
> I know this is somewhat unrelated, but I hope the team who do the frontend work on Grafana Cloud update the helm install (and auto token creation with the correct scopes) to celebrate the 1.0 release shortly after merge.

It's on my list 😉
