### ISSUE TITLE
Scraping pprof profiles: clustering=true + discovery.kubernetes selectors misconfiguration

### ISSUE THREAD

**Issue by Bruno-DaSilva** [grafana/k8s-monitoring-helm#459]
I noticed after deploying profiling with pprof scraping enabled, my profiles were not properly being scraped. The daemonset pods that ran along side my applications were not showing the correct set of scrape targets, despite them being supplied as input.

I believe this is because of these two configurations. In particular, selecting ONLY the pods on the same node, combined with trying to spread them out with clustering enabled=true. If my reading of the docs is correct, clustering expects all daemonset pods to have the same input target list (not each agent pod having only the same workloads on the same node).

```
discovery.kubernetes "pprof_pods" {
      selectors {
        role = "pod"
        field = "spec.nodeName=" + env("HOSTNAME")
      }
      role = "pod"
    }
```

```
pyroscope.scrape "pyroscope_scrape_cpu" {
      targets = concat(discovery.relabel.pprof_pods_cpu_default_name.output, discovery.relabel.pprof_pods_cpu_custom_name.output)
      clustering {
        enabled = true
      }

      profiling_config {
        profile.process_cpu {
          enabled = true
        }
      }

      forward_to = [pyroscope.write.profiles_service.receiver]
    }
```

FYI I ran into this on the `feat/alloy` branch, if that makes a difference :) 

I believe the solution is to either set clustering enabled=false or remove the node selector. When I do so locally, scraping is now working.

cc @petewall (I see you added profiling 2 weeks ago in https://github.com/grafana/k8s-monitoring-helm/pull/446 and also working on `feat/alloy`)

**Comment by petewall** [comment]
I'll remove clustering, since we're deployed as a daemonset anyway.

**Comment by Bruno-DaSilva** [comment]
yay, thanks @petewall !
