### ISSUE TITLE
Add sane defaults to reduce cardinality

### ISSUE THREAD

**Issue by davhdavh** [grafana/k8s-monitoring-helm#46]
The current config will generate close to 10.000 metrics on an near empty cluster.

Much of the problem is that something like the cadvisor scrape for networking will generate a series per pod per interface per device per xxx easily generating 1000-2000 unique metrics.

The reality is that by far most of these unique labels are not used.

**Comment by davhdavh** [comment]
What I am thinking here, is a list of predefined sets of metrics reduction:
* All (current)
* Pod (should be default, expecting ~50% reduction in unique metrics series)
* Workload (pod level metrics removed, 75% reduction)
* Namespace (workload level metrics remove, 90% reduction)

some of the charts are using some secret metrics. e.g. `node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate` is there anywhere I can find the specification on this?

**Comment by davhdavh** [comment]
Preliminary testing on a single node cluster shows a bit better than 50% savings without loss of any charts.
WITH POD-level rules: 6.94k unique metrics, 5.80k as k8s intg, 122 as linux intg.
WITHOUT rules: 13.7k unique metrics, 11.9k as k8s intg, 796 as linux intg. - but logs say it gets rate limited at 15k (im just testing on a free account)
I'm fairly certain we can cut another 10-20% without loss of charts by focusing on the allowLists a bit more.

**Comment by davhdavh** [comment]
Rules used
[custom_rules.zip](https://github.com/grafana/k8s-monitoring-helm/files/12249711/custom_rules.zip)

**Comment by davhdavh** [comment]
Workload level rules (I changed a bit, so pod-level is slightly different from above)
WITH POD-level rules: 6.23k unique metrics, 5.11k as k8s intg, 105 as linux intg.
WITH workload-level rules: 4.55k unique metrics, 3.52k as k8s intg, 105 as linux intg.
This WILL break some charts, but if you just care about an overview of the metrics at low cost, that might be what you want.

**Comment by davhdavh** [comment]
WITH namespace-level rules: 1.62k unique metrics, 1.0k as k8s intg, 105 as linux intg.

**Comment by petewall** [comment]
This is very interesting! Thanks for digging into this.

The "secret metrics" are recording rules are set from this repo: https://github.com/grafana/kubernetes-mixin. If you search there, you can find the metrics that are used by that rule.

**Comment by davhdavh** [comment]
Yeah. I found them in the UI. Recording rules they are called and for some odd reason specified under alerts.

**Comment by hatf0** [comment]
+1. Tested this on a decently-in-use cluster and produced 719k metrics, 40gb of logs in sub-24 hours. Thank god for the free Grafana Cloud trial.

**Comment by davhdavh** [comment]
Ok, first thing... The magic incantation of queries in grafana to figure out what is making a mess is these 2 promql:
```promql
count by (job) ({cluster="clusterid"}) 
topk(20, count by (job,__name__) ({cluster="clusterid"}))
```
That lets us split it down per "job". Let's do some testing on my simple cluster, single linux node and single windows node, pretty much just running 1 app with all of the support for that.

# cadvisor
The baseline for this is 8954 unique metrics for cadvisor. With the network metrics taking up 6 x 922 metrics alone.

## Dropping metrics
First off, it seems at some point someone added some extra metrics to all of the outputs, which doubled the amount of metrics, and then people fixed the graphs but didn't filter them out at base level. See https://github.com/google/cadvisor/issues/2688

```
        rule {
          source_labels = ["__name__","image"]
          separator = "@"
          regex = "(container_cpu_.*|container_fs_.*|container_memory_.*|container_network_.*)@"
          action = "drop"
        }
        rule {
          source_labels = ["__name__","container"]
          separator = "@"
          regex = "(container_cpu_.*|container_fs_.*|container_memory_.*)@"
          action = "drop"
        }
```

Second, we want to drop some of the useless labels, and by dropping I mean give them all the same name, because some metrics check that they are `!=""`

```
        rule {
          source_labels = ["__name__"]
          regex = "container_cpu_.*|container_fs_.*|container_memory_.*|container_network_.*"
          target_label = "id"
          replacement = "NA"
        }
        rule {
          source_labels = ["__name__"]
          regex = "container_cpu_.*|container_fs_.*|container_memory_.*|container_network_.*"
          target_label = "image"
          replacement = "NA"
        }
        rule {
          source_labels = ["__name__"]
          regex = "container_cpu_.*|container_fs_.*|container_memory_.*|container_network_.*"
          target_label = "name"
          replacement = "NA"
        }
        rule {
          source_labels = ["__name__"]
          regex = "machine_memory_bytes"
          target_label = "boot_id"
          replacement = "NA"
        }
        rule {
          source_labels = ["__name__"]
          regex = "machine_memory_bytes"
          target_label = "system_uuid"
          replacement = "NA"
        }
```

Third, for network and storage, the graph queries filters out non-physical devices/interfaces anyway, so we can throw those away at collection time. **Notice there is a bug in the graph queries that double counts storage metrics when the drive is both mounted on a /dev/sdX and comes from /dev/md-Y**. So we drop the `md-X` metrics here also.

```
        rule {
          source_labels = ["__name__", "device"]
          separator = "@"
          regex = "container_fs_.*@(/dev/)?(mmcblk.p.+|nvme.+|rbd.+|sd.+|vd.+|xvd.+|dasd.+)"
          target_label = "__keepme"
          replacement = "1"
        }
        rule {
          source_labels = ["__name__", "__keepme"]
          separator = "@"
          regex = "container_fs_.*@"
          action = "drop"
        }
        rule {
          source_labels = ["__name__"]
          regex = "container_fs_.*"
          target_label = "__keepme"
          replacement = ""
        }

        rule {
          source_labels = ["__name__", "interface"]
          separator = "@"
          regex = "container_network_.*@(en[ospx]|wlan|eth)[0-9].*"
          target_label = "__keepme"
          replacement = "1"
        }
        rule {
          source_labels = ["__name__", "__keepme"]
          separator = "@"
          regex = "container_network_.*@"
          action = "drop"
        }
        rule {
          source_labels = ["__name__"]
          regex = "container_network_.*"
          target_label = "__keepme"
          replacement = ""
        }
```
### Result

1609  **82% REDUCTION** unique metrics for cadvisor keeping FULL fidelity to graphs.

The top metrics using only 91 unique label combinations (ie, appx the amount of pods running).

### Further optimizations

Prometheus (Grafana agent) data collection model is very tied both the collection and reporting and thus you cannot filter on values (ie, why do you need to report all of the 0 metrics for dropped network packets for each pod?!?), nor can you aggregate at collection time on metrics (ie, if there are 7 physical /dev/sdX devices, the number of metrics will explode by 600%, but the graph stays the same).

This IS possible if the collection is done via OpenTelemetry collector which has a different data model that does let you apply transformations including aggregations.

**Comment by davhdavh** [comment]
# kube-state-metrics

This is a bit more controversial, because the metrics that this reports is absolutely horrendous from minimizing the amount of metrics collections

## Baseline

3230 unique metrics.

## Optimizations

First, lets clean up some of those labels we are never going to use:

```
        rule {
          source_labels = ["__name__"]
          target_label = "uid"
          replacement = "NA"
        }
        rule {
          source_labels = ["__name__"]
          target_label = "image_id"
          replacement = "NA"
        }
        rule {
          source_labels = ["__name__"]
          target_label = "image"
          replacement = "NA"
        }
        rule {
          source_labels = ["__name__"]
          target_label = "image_spec"
          replacement = "NA"
        }
        rule {
          source_labels = ["__name__"]
          regex = "kube_pod_info|kube_pod_owner"
          target_label = "created_by_name"
          replacement = "NA"
        }
        rule {
          source_labels = ["__name__"]
          regex = "kube_pod_container_info"
          target_label = "container_id"
          replacement = "NA"
        }
        rule {
          source_labels = ["__name__"]
          regex = "kube_pod_info"
          target_label = "host_ip"
          replacement = "NA"
        }
        rule {
          source_labels = ["__name__"]
          regex = "kube_pod_info"
          target_label = "pod_ip"
          replacement = "NA"
        }
```

Second, `kube_pod_status_reason` and `kube_pod_status_phase` has an extreme number of metrics with X number of state per pod. Let's take the harvester and get rid of all of the ones that are unused in the graphs and alerts. We also map `Unknown` into `Failure`.

```
        rule {
          source_labels = ["__name__","reason"]
          separator = "@"
          regex = "kube_pod_status_reason@Evicted"
          target_label = "__keepme"
          replacement = "1"
        }
        rule {
          source_labels = ["__name__", "__keepme"]
          separator = "@"
          regex = "kube_pod_status_reason@"
          action = "drop"
        }
        rule {
          source_labels = ["__name__"]
          regex = "kube_pod_status_reason"
          target_label = "__keepme"
          replacement = ""
        }
        rule {
          source_labels = ["__name__","phase"]
          separator = "@"
          regex = "kube_pod_status_phase@Unknown"
          target_label = "phase"
          replacement = "Failed"
        }
        rule {
          source_labels = ["__name__","phase"]
          separator = "@"
          regex = "kube_pod_status_phase@(Pending|Running|Failed)"
          target_label = "__keepme"
          replacement = "1"
        }
        rule {
          source_labels = ["__name__", "__keepme"]
          separator = "@"
          regex = "kube_pod_status_phase@"
          action = "drop"
        }
        rule {
          source_labels = ["__name__"]
          regex = "kube_pod_status_phase"
          target_label = "__keepme"
          replacement = ""
        }
```

Third, the default list of metrics to include is a bit too permissive, and we could clean up that list, but lets stick to the same way of handling the rules. In particular all of the replicasets (which in a default cluster you will have ~10x the number of pods) has a great many useless metrics. We also don't need metrics for each annotation or label.

```
        rule {
          source_labels = ["__name__"]
          regex = "kube_replicaset.*"
          action = "drop"
        }
        rule {
          source_labels = ["__name__"]
          regex = "kube_.*(annotations|labels|created)"
          action = "drop"
        }
        rule {
          source_labels = ["__name__"]
          regex = "kube_pod_container_info"
          action = "drop"
        }
        rule {
          source_labels = ["__name__"]
          regex = "kube_pod_container_status_restarts_total"
          action = "drop"
        }
```

Similarly, we have some metrics that exploded to the hundreds, but with very very little value that isn't already covered by other alerts. ie, you really should have an alert from argo deployments when it does rollback, and thus we can drop these couple of hundred metrics that deals exclusively with rollbacks to former replicasets.

```
        rule {
          source_labels = ["__name__"]
          regex = "kube_.*_status_replicas.*"
          action = "drop"
        }
```

## Result

1184 (** 63% REDUCTION**) unique metrics, with _minimum_ loss of fidelity and loss of _some_ alerts.

## Further optimizations

`kube-state-metrics` would really benefit from basic aggregation and drop of all 0 metrics.

**Comment by davhdavh** [comment]
# node-exporter

## Baseline

791 unique metrics

## Optimizations

Looking at the metrics, there is not that much to optimize here. The only thing I could find is reporting of non-physical storage, and thus that is what we remove.

```
        rule {
          source_labels = ["__name__", "fstype"]
          separator = "@"
          regex = "node_filesystem.*@tmpfs"
          action = "drop"
        }
        rule {
          source_labels = ["__name__","mountpoint"]
          separator = "@"
          regex = "node_filesystem.*@/"
          target_label = "__keepme"
          replacement = "1"
        }
        rule {
          source_labels = ["__name__","__keepme"]
          separator = "@"
          regex = "node_filesystem.*@"
          action = "drop"
        }
```

## Result

105 ( **86% reduction** ) unique metrics with **no** loss of fidelity.

## Further optimizations

I don't see any

**Comment by davhdavh** [comment]
# Opencost

I choose to disable this, because it doesn't work out-of-the-box. Thus saving 100% of the metrics (152 unique metrics).

## Further optimizations

The way that it is put together is that metrics will be uploaded into grafana, then opencost will download those metrics, analyze them and export a new set of metrics that then gets uploaded to grafana. It really should just scrape the metrics itself and then report those. That would also get rid of the need to have write permissions to the grafana cloud metrics.

**Comment by davhdavh** [comment]
# Kubelet

Kubelet mostly takes up metrics from not using native histograms, and I do not really know how that could be optimized.

Also, it only uses ~400 unique metrics to begin with, of which about 80% scales linear by number of nodes, so not much room for improvement.

**Comment by davhdavh** [comment]
# Conclusion

It is trivial to add a bunch of rules that cut the number of unique metrics by 75% with almost no loss of fidelity.

In my test cluster, it goes from (8954+3230+791+152+408) = 13535 unique metrics to (1609+1184+105+408) = 3306.
A total of 76% reduction in unique metrics. 👍 👍 👍 👍 
Also goes from breaking the 10k free limit (which is actually 15k) to something where you are able to use it comfortably in a mini cluster and have room for some application specific metrics.

**Comment by pl4nty** [comment]
+1, this has blocked our migration from OTel collector to grafana agent in a multi-cluster scenario. I expected that the chart would only collect metrics for the integration-provided dashboards etc, or at least have an option to do so.

**Comment by danielloader** [comment]
To echo the above, it's been quite shocking to see how many metrics are emitted with a default install of this stack. It's entirely unusable when you combine a cluster with Karpenter and start having transient and numerous node counts. 

Ended up with more overages in metrics cost alone than the EC2 bill for spawning 20 small instances to do jobs for ~20mins a go.

**Comment by skl** [comment]
For Grafana Cloud customers, there is [Adaptive Metrics](https://grafana.com/products/cloud/metrics/prometheus-cardinality-optimization/) which is capable of analysing account-specific usage. It's difficult to find a solution which fits all use cases, as we've also had comment that there aren't enough metrics emitted by default.

In this repo we've added examples which allow more control over the number of series, for example in combination with the research in this thread above:

- [Custom Allow Lists](https://github.com/grafana/k8s-monitoring-helm/tree/main/examples/custom-allow-lists)
- [Custom Config](https://github.com/grafana/k8s-monitoring-helm/tree/main/examples/custom-config)
- [Extra Rules](https://github.com/grafana/k8s-monitoring-helm/tree/main/examples/extra-rules)
- [Scrape Intervals](https://github.com/grafana/k8s-monitoring-helm/tree/main/examples/scrape-intervals)
- [Specific Namespace](https://github.com/grafana/k8s-monitoring-helm/tree/main/examples/specific-namespace)

**Comment by danielloader** [comment]
Appreciated, useful information in those links.

**Comment by hatf0** [comment]
Just so all are aware, we received a bill from Grafana Cloud for $2k+ because of this Helm chart. Be very, very, very careful using this, and monitor your DPM very closely when using this chart. It's very easy to get a giant unexpected bill 😦

**Comment by danielloader** [comment]
Can imagine if you install this on a single cluster that's very busy with hundreds of nodes you'll blow past the allotted metrics in seconds - that said I guess it would be my fault for not starting smaller in that scenario. 

No one size fits all I guess.

**Comment by hatf0** [comment]
@danielloader 
> Can imagine if you install this on a single cluster that's very busy with hundreds of nodes you'll blow past the allotted metrics in seconds

Actually .. we blew past the allotted metrics with only 20 nodes. Came as a big shock to us, since we're a relatively small shop.

**Comment by rtrindvg** [comment]
Same here. 2 clusters (staging + prod), 3 nodes each, with less than 10 custom services on it + this helm. It was enough to pass the 20k metrics. After using the workaround provided here, it became more manageable, but it still looks to be collecting so much more with just the default dashboards and alerts.

Adaptive metrics game 3 metrics to reduce, which corresponded to less than 1% of the metrics, and all the other recommendations from the documentation leave me to identify if the series or cardinality makes sense, but since I did not created neither the metrics, nor the alerts (because they are all the defaults from the helm + the default actions from the guided install from Grafana), it's hard to see what will break if I reduce something in the ingestion phase without breaking the dashboards or alerts.

I think it's really important the default k8s experience to be revised to include as little metrics/dashboards/alerts as necessary and give the liberty to each one to expand the capabilities as needed, instead of this bloated state we have today.

**Comment by skl** [comment]
Thanks all for the constructive feedback, this is healthy discussion. If anyone would like to share their (redacted/generalised) values file here to help others, I'm sure that would be appreciated.

There have been some recent updates specific to Grafana Cloud which may be of interest:

- New [Grafana Cloud Cost Management Hub](https://grafana.com/blog/2023/11/14/grafana-cloud-cost-management-tools-for-metrics-logs-and-more/)
- New [Kubernetes Monitoring Cardinality dashboard](https://grafana.com/docs/grafana-cloud/monitor-infrastructure/kubernetes-monitoring/use-dashboards/)

This is in addition to the [cardinality management dashboards](https://grafana.com/blog/2022/02/28/how-to-manage-cardinality-with-out-of-the-box-dashboards-in-grafana-cloud/) previously announced.

**Comment by danielloader** [comment]
Just to say because it can sound negative in such threads - as the sole and lead platform engineer at a startup - this grafana cloud stack has been a life saver. 

I'm glad it's a product after using grafana and co for years in other companies and it allows me to focus on delivering the value add at work.

That said, a startup of 10 people, or even 2 people, if they adopt kubernetes at all will slam into the top end of the 20k limit nearly instantly as anyone running kubernetes is at the least going to be running two clusters.

I know it's a cop out and the easy answer from a customer perspective but if kubernetes is such a huge problem on the metrics front just because of all the moving parts and high cardinality metrics it entails - reviewing the 20k baseline for metrics might be on the cards.

The above suggestions of using the functionality in the platform to aggregate noisy but largely unused metrics is definitely welcome and I've actioned those.

I'm intending to stick around with this product in a professional setting because functionally it's hitting the requirements. Though it's a tiny bit dispiriting being an experienced engineer running two clusters with two dozen nodes in total and blasting way past the metrics quota.

Thanks anyway for being involved with improving this situation.

**Comment by edas-smith** [comment]
+1 would definitely be a nice thing to add.

**Comment by djtecha** [comment]
Maybe we could think about adding a `minimal` flag that starts with bare minimum metrics (CPU, memory, disk io) with a guide on adding rule sets to grow from there? I understand it might be problematic to break users that currently expect ALL metrics here so some type of bool might be the way to go to make everyone happy.

**Comment by skl** [comment]
I like the idea of having a choice of the default (as it is now) versus some kind of minimal option. It's just that we have a fair-sized backlog at the moment and there's an exercise required here to discover and document the minimum working configuration for the majority case, which takes time 😄

**Comment by juupas** [comment]
@davhdavh Until #326 is finished, where do you actually put these rules? Can they all go to `metrics.extraRelabelingRules` in the values file?

**Comment by davhdavh** [comment]
Probably easiest to show you my current config [values.zip](https://github.com/grafana/k8s-monitoring-helm/files/14022635/values.zip)

**Comment by petewall** [comment]
Thank you, @davhdavh for putting in a lot of heavy lifting for the research and tuning of these metrics!

**Comment by sidewinder12s** [comment]
FYI, I dug into this more and think I found why some of these labels are the way they are. 

This is also what containerd looks like but is likely to be potentially different by container runtime.

With the `container_cpu_usage_seconds_total`:

1st Metric: Overall Pod cgroup
2nd Metric: Pause Container
3rd Metric: Actual Container

```log
container_cpu_usage_seconds_total{container="",cpu="total",id="/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-pod539bf93f_88df_454e_9e05_e55678d4aae4.slice",image="",name="",namespace="karpenter",pod="karpenter-69466cdcd8-p9v6f"} 114232.482769885 1709152176827
container_cpu_usage_seconds_total{container="",cpu="total",id="/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-pod539bf93f_88df_454e_9e05_e55678d4aae4.slice/cri-containerd-913c11dffe96a0e6f7521ec06663c5d22132133b1bd5205f67caf59d305fc5c8.scope",image="066635153087.dkr.ecr.il-central-1.amazonaws.com/eks/pause:3.5",name="913c11dffe96a0e6f7521ec06663c5d22132133b1bd5205f67caf59d305fc5c8",namespace="karpenter",pod="karpenter-69466cdcd8-p9v6f"} 0.100686752 1709152174842
container_cpu_usage_seconds_total{container="controller",cpu="total",id="/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-pod539bf93f_88df_454e_9e05_e55678d4aae4.slice/cri-containerd-0c166c1b9b48eb5e90eb308e628ba1520520040467fb1a3d8a0085f0a0a91f81.scope",image="public.ecr.aws/karpenter/controller@sha256:fda1fb00daeb139e57c30a6e8ddfc0f917307ee426883ceb450502949a80f543",name="0c166c1b9b48eb5e90eb308e628ba1520520040467fb1a3d8a0085f0a0a91f81",namespace="karpenter",pod="karpenter-69466cdcd8-p9v6f"} 114232.705052401 1709152180077
```

It seems that historically most dashboards either ignore or filter out both the pause container (minimal usage & largely a detail of the container runtime) and overall cgroup metrics in favor of the container metrics, then rebuilding the pod metrics in aggregation. 

Some detail here: https://github.com/google/cadvisor/issues/2249

**Comment by sidewinder12s** [comment]
Another cleanup I'd found was that at least for containerd + AWS VPC CNI, cAdvisor was duplicating all container metrics for hostNetwork pods. 

I added a rule to drop non-eth0 metrics so the extra series get dropped and then also dropped the interface label because it wasn't that useful in the context of how the AWS VPC CNI manages networking (hostNetwork pods should be using the hosts default interface, but all these details likely are highly dependent on container runtime and container network).

```
        - sourceLabels: ["__name__","interface"]
          separator: "@"
          regex: "(container_network_.*)@(eth[1-9].*)"
          action: drop
        # Drop interface label, ethernet interface is not that useful in the context of a pod for the AWS VPC CNI
        - regex: "interface"
          action: labeldrop
```

**Comment by danielloader** [comment]
@sidewinder12s good catch, where did you put this in your helm chart values?

**Comment by sidewinder12s** [comment]
> [@sidewinder12s](https://github.com/sidewinder12s) good catch, where did you put this in your helm chart values?

Raw Grafana config rules attached to `metrics.cadvisor.extraMetricRelabelingRules`

**Comment by danielloader** [comment]
Just had a look and found out that the format for these rules needs to use the alloy syntax instead of a yaml array prometheus style, took a little while to work out why it didn't work.

**Comment by seanmorton** [comment]
The default metric allow lists that came from this discussion  and added in https://github.com/grafana/k8s-monitoring-helm/pull/326 luckily made it over from v1 to v2 of the chart, but I still found it to be on the expensive side. I did some further tuning and reduced costs significantly, while still keeping most dashboards and rules functional. Here's the values in case it helps anyone:

https://github.com/pelotech/foundation/blob/73ce69363c7d6b704557363649130654877fd939/gitops/components/grafana-k8s-monitoring/resources.yaml#L25
