### ISSUE TITLE
Cluster name for opencost cost is 'default-cluster'

### ISSUE THREAD

**Issue by davhdavh** [grafana/k8s-monitoring-helm#48]
It seems the cluster.name config is not applied to opencost

**Comment by skl** [comment]
@petewall are you aware of this still being an issue? In my test cluster it seems cluster label is working for opencost metrics:

```
opencost_build_info{cluster="k8sdev-aws-helm",instance="windows-split-opencost.default.svc:9003",job="integrations/kubernetes/opencost",revision="4bd6485",version="1.105.0"}
```

**Comment by peterolivo** [comment]
I think @davhdavh is mentioning the opencost CLUSTER_ID env https://github.com/opencost/opencost-helm-chart/blob/2afac185999e7adc0cf2a4085c629985467587d4/charts/opencost/templates/deployment.yaml#L89

https://github.com/grafana/k8s-monitoring-helm/blob/1152eb8ccfd2ac946a357df6841b947606e7ac33/examples/otel-collector/output.yaml#L1459C39-L1459C39
