### ISSUE TITLE
Inline cluster name

### ISSUE THREAD

**Issue by petewall** [grafana/k8s-monitoring-helm#54]
I admit, I was being cute when I put the cluster name in the config map and then mounted that into the agent container.

I think the original idea was to set it in one place, but the cluster name really shouldn't change much.

The cluster name being piggy-backed into the same ConfigMap as the Agent configuration means that it's harder for users to use their own ConfigMaps.

**Comment by davhdavh** [comment]
Are we not back to the same argument? https://github.com/grafana/k8s-monitoring-helm/issues/45#issuecomment-1660522533
The point of this helm should be to provide a way to deliver quality k8s metrics/logs to the pre-defined grafana dashboards, and within that framework enable collection of other metrics/logs/traces to be delivered to grafana.
The keywords being **within that framework**.
If people want another way to handle their metrics/logs/traces, they should install another grafana agent or otel collector, or prometheus. Luckily k8s is a great cluster system, so they can co-exist with no issues.

If it wasn't clean, I am totally fine with the way the cluster.name is handled in the helm.

**Comment by davhdavh** [comment]
FYI this change is pretty annoying, because you can no longer make a config for the extraConfig section that is cluster independent.

e.g. here an example, where I want to use the same traefik integration for all of my clusters

```
  extraConfig: |-
    discovery.relabel "traefik" {
      targets = discovery.kubernetes.services.targets
      rule {
        source_labels = ["__meta_kubernetes_service_label_app_kubernetes_io_name"]
        regex = "traefik"
        action = "keep"
      }
      rule {
        source_labels = ["__meta_kubernetes_service_label_app_kubernetes_io_component"]
        regex = "metrics"
        action = "keep"
      }
      rule {
        source_labels = ["__name__"]
        replacement   = local.file.cluster_name.content
        target_label  = "cluster"
      }
    }
    
    prometheus.scrape "traefik" {
      job_name   = "integrations/traefik"
      targets  = discovery.relabel.traefik.output
      forward_to = [prometheus.relabel.traefik.receiver]
      scrape_interval = "2m"
    }

```
