### ISSUE TITLE
Add config support for new live debugging feature

### ISSUE THREAD

**Issue by stefanandres** [grafana/k8s-monitoring-helm#605]
It would be nice to be able to enable the new live debugging feature.

https://grafana.com/docs/alloy/latest/reference/config-blocks/livedebugging/

**Comment by petewall** [comment]
You can easily do this today by setting:
```
extraConfig: |
  livedebugging {
    enabled = true
  }
```

also to `logs.extraConfig` and `logs.cluster_events.extraConfig`

**Comment by stefanandres** [comment]
Since I deploy k8s-monitoring via ArgoCD to multiple environments via an ArgoCD ApplicationSet this is only a workaround.

I already set extraConfig to some of those environments. Since this variable is only a string and not a map, I cannot use a base values.yaml for this because this setting wouldn't be merged into all environments and I would need to put this config explicitly into all environment.yaml files instead of just a single file.

So having this configurable as dedicated helm variable would be beneficial.

**Comment by petewall** [comment]
Made it happen! Look for it in 1.4.1 coming soon.

**Comment by stefanandres** [comment]
Awesome, thanks! 🙂
