### ISSUE TITLE
Podmonitor and Servicemonitor Metrics are missing Cluster name

### ISSUE THREAD

**Issue by stefan-schweer** [grafana/k8s-monitoring-helm#63]
Currently the metrics scraped via pod and servicemonitors don't get the cluster_name label added, and i can't find any hint in the docs how to add that.

**Comment by stefan-schweer** [comment]
Works, thanks!!!

**Comment by petewall** [comment]
Thank you for pointing out the issue. Glad we could get it fixed quickly for you.
