### ISSUE TITLE
loki is not picking the logs from custom locations

### ISSUE THREAD

**Issue by LingamEswar** [grafana/k8s-monitoring-helm#632]
Hi Team,

We have deployed monitoring helm chart of version 1.0.0 . 
We want the loki agent to pick the logs from specified location from the node, instead of default location. How can we achieve this. 
I have seen the properties that i can place in values.yaml, but didnt found the suitable one. Can you please suggest here.

**Comment by petewall** [comment]
Can you be more specific? Why does `/var/log/pods` not work? Or do you want those logs as well as files from a different location?

**Comment by LingamEswar** [comment]
> Can you be more specific? Why does `/var/log/pods` not work? Or do you want those logs as well as files from a different location?

We are processing the logs generated by pods and placing them in the separate folder and we want loki to read those logs and send them to grafana cloud. So can we configure the logs path?

**Comment by petewall** [comment]
`/var/log/pods` is hardcoded at the moment, and it expects the path to be:
`/var/log/pods/.*<pod UID>/<container name>/*.log`
Often the real path is: `/var/log/pods/<namespace>_<pod_name>_<pod UID>/<container name>/*.log`

Are the log files for your cluster in the same path structure? How would one correlated pods to log files?

**Comment by LingamEswar** [comment]
> `/var/log/pods` is hardcoded at the moment, and it expects the path to be: `/var/log/pods/.*<pod UID>/<container name>/*.log` Often the real path is: `/var/log/pods/<namespace>_<pod_name>_<pod UID>/<container name>/*.log`
> 
> Are the log files for your cluster in the same path structure? How would one correlated pods to log files?

@petewall  ok tell me the scenario. 
We want to push the logs to loki only for the container who status is other than success, as i see the "extraRelabelingRules" can read only pod_phase and pod_ready, those are not helping us to our requirement. Because till the pod gets into ready state the logs are pushing. So we dont want that as well. So we have our internal script which will process the logs present in /var/log/pods/ and identifies logs related to failed containers and move to the other folder . So we want loki to point to that folder and send those logs. 

Let me know, if you have any thoughts/suggestions that can help to our requirement.

**Comment by petewall** [comment]
> So we have our internal script which will process the logs present in /var/log/pods/ and identifies logs related to failed containers and move to the other folder.

What is the path of the other folder? Give me an example of a log file in that directory structure.

**Comment by LingamEswar** [comment]
> > So we have our internal script which will process the logs present in /var/log/pods/ and identifies logs related to failed containers and move to the other folder.
> 
> What is the path of the other folder? Give me an example of a log file in that directory structure.

our new location is /tmp/logs/filteredLogs . 
Log file will be the same file that is generated by the container. We are not changing the log file . We are just picking the required files and moving them to different folder that's it.

**Comment by petewall** [comment]
Try adding this to your values file:
```yaml
alloy-logs:
  alloy:
    mounts:
      varlog: false
      extra:
        - name: failed-pod-logs
          mountPath: /var/logs/pods
  controller:
    volumes:
      extra:
        - name: failed-pod-logs
          hostPath:
            path: /tmp/logs/filteredLogs
```

This will disable the default `/var/log` volume mount and instead mount `/tmp/logs/filteredLogs` on the node to `/var/logs/pods`.

**Comment by LingamEswar** [comment]
@petewall Added the configuration as suggested. Below is the updated values.yaml file.
`cluster:
  name: mycluster

externalServices:
  prometheus:
    host: <host>
    basicAuth:
      username: "<userName>"
      password: "<pass>"
  loki:
    host: <host>
    basicAuth:
      username: "<userName>"
      password: "<pass>"
alloy-logs:
  alloy:
    mounts:
      varlog: false
      extra:
        - name: failed-pod-logs
          mountPath: /var/logs/pods
  controller:
    volumes:
      extra:
        - name: failed-pod-logs
          hostPath:
            path: /tmp/logs/filteredLogs`
With this config, loki is not reading the logs from /var/logs/pods and also /tmp/logs/filteredLogs. I have moved the log generated from  /var/logs/pods  to /tmp/logs/filteredLogs and given full permissions to the file. But logs are not getting uploaded.

**Comment by petewall** [comment]
Check the pod logs for the alloy-logs pods (with kubectl logs). They should say things like:
```
level=info msg="tail routine: started"...
```
when it finds a file to open and read from. If there are none of those lines, it's not finding the file.

Can you share the full path to one of the files that have been moved to `/tmp/logs/filteredLogs`?

**Comment by petewall** [comment]
Did you get this working?
