### ISSUE TITLE
Replace Node Exporter with Alloy? 

### ISSUE THREAD

**Issue by brauhausdc** [grafana/k8s-monitoring-helm#659]
Part suggestion and part note in case anyone else runs into it -- I was working to deploy this on a cluster which included several nodes that were running CEPH - one of the options with current versions of CEPH is to have nodes run Node Exporter. This caused my attempt to deploy the helmchart for grafana-k8s-monitoring to fail as it couldn't start node exporter due to a conflict on the port. My immediate solution was to disable the CEPH associated node-exporter. 

Better though, I think, might be to consider using Alloy rather than node-exporter here, unless there's some specific reason not to. Alloy includes node-exporter capabilities under the covers, if I'm not mistaken?

**Comment by petewall** [comment]
Thanks for posting this!
There are a few reasons why this chart prefers to deploy its own copy of Node Exporter and not use Alloy's built-in version of `prometheus.exporter.unix` (essentially Node Exporter itself).
First is separation of concerns. Node Exporter can do it's thing: building node metrics, Alloy does its thing: being a telemetry data collector.
Second is deployment pattern. If we use Alloy as Node Exporter, we need to deploy Alloy as a daemonset with elevated permissions to get access to the node. So, like point 1, we leave that to Node Exporter, which has a smaller footprint than Alloy.
Third, and actually the biggest reason is that sometimes Node Exporter already exists in the cluster, so let's make it simple to use what's already there and not duplicate work. You can configure this chart to still gather Node Exporter metrics, but not deploy Node Exporter itself.

If you set this:
```
metrics:
  node-exporter:
    labelMatchers: ...    # Set so that it matches the Node Exporter pod instances in your cluster
prometheus-node-exporter:
  enabled: false.  # Disables the deployment of Node Exporter
```

It'll skip deploying NE, but tell Alloy how to find the one that already exists in the system.

**Comment by petewall** [comment]
Quick question, because I'm not as familiar with CEPH. Does Node Exporter show up as a pod in the cluster, or is it installed on the node, outside of Kubernetes? If the former, the above config snippet should work. If the latter, we might need to do a different path (basically, find all nodes and manually set the Node Exporter port number), but I can help with that, too.

Finally, if all else fails, we can configure the Helm chart to deploy Node exporter again, but use an alternate port number.

**Comment by brauhausdc** [comment]
Re: CEPH — like many things “it depends” — Ceph has several ways it can be installed. What seems to be the current generally recommended method is to use “cephadm” which is (basically) a python script which will setup a set of docker containers (so, outside of Kubernetes) for each of the ceph “services” - one of which is Node Exporter. It also has (optional) Prometheus and Grafana services.--Dan BrownOn Jul 28, 2024, at 10:58, Pete Wall ***@***.***> wrote:﻿
Quick question, because I'm not as familiar with CEPH. Does Node Exporter show up as a pod in the cluster, or is it installed on the node, outside of Kubernetes? If the former, the above config snippet should work. If the latter, we might need to do a different path (basically, find all nodes and manually set the Node Exporter port number), but I can help with that, too.
Finally, if all else fails, we can configure the Helm chart to deploy Node exporter again, but use an alternate port number.

**Comment by brauhausdc** [comment]
I’d probably ask whether the Node Exporter thats getting installed with the k8s-monitoring-helm needs to have port 9100 exposed externally? --Dan BrownOn Jul 29, 2024, at 05:40, Daniel H Brown ***@***.***> wrote:﻿
Re: CEPH — like many things “it depends” — Ceph has several ways it can be installed. What seems to be the current generally recommended method is to use “cephadm” which is (basically) a python script which will setup a set of docker containers (so, outside of Kubernetes) for each of the ceph “services” - one of which is Node Exporter. It also has (optional) Prometheus and Grafana services.--Dan BrownOn Jul 28, 2024, at 10:58, Pete Wall ***@***.***> wrote:﻿

Quick question, because I'm not as familiar with CEPH. Does Node Exporter show up as a pod in the cluster, or is it installed on the node, outside of Kubernetes? If the former, the above config snippet should work. If the latter, we might need to do a different path (basically, find all nodes and manually set the Node Exporter port number), but I can help with that, too.

Finally, if all else fails, we can configure the Helm chart to deploy Node exporter again, but use an alternate port number.

**Comment by petewall** [comment]
Node Exporter needs `hostNetwork` in order to gather network metrics on that node, but there's no reason why we cannot have it use an alternate port number.

I think if you set:
```
prometheus-node-exporter:
  service:
    port: 9101
    targetPort: 9101
```

**Comment by brauhausdc** [comment]
Thanks - will give that a go. Though - is there any reason that Alloy (which I’m assuming is in use to scrape NE and forward to Grafana Cloud) couldn’t talk to NE inside of Kubernetes? 

As a non-kubernetes example, I’m doing something similar with docker compose - I’ve setup a private “monitoring” network so that various containers talk to each other across that, rather than needing to expose ports externally on the host itself.

**Comment by petewall** [comment]
If you can access the NE metrics endpoint from within a pod, then you should totally be able to have Alloy use that instead.
We currently discover NE by finding all pods, then filtering down to Node Exporter pods, then scraping them for metrics.
An alternative we could look at is discover all Nodes, then append the Node Exporter port onto the Node IP.
Can you check to see if that's a usable solution?

From within a pod, see if you can `curl <nodeIP:9100>/metrics`
