### ISSUE TITLE
Unable to disable metric suffixes

### ISSUE THREAD

**Issue by fhqwhgadss** [grafana/k8s-monitoring-helm#665]
Hi!

I'm unable to find any way to disable the `add_metric_suffixes` argument for the `metrics_converter` [otelcol.exporter.prometheus](https://grafana.com/docs/alloy/latest/reference/components/otelcol/otelcol.exporter.prometheus/) component through the helm chart.

Would it be possible to add this as an option in the chart?

**Comment by petewall** [comment]
Everybody to the limit!
PR incoming.
