### ISSUE TITLE
Consider using "job" instead of a naked pod for pre-install hook

### ISSUE THREAD

**Issue by shevelevs** [grafana/k8s-monitoring-helm#668]
If a "Job" resource is used, retry policy can be more flexible. In our deployment model we occasionally run into situations when a hook pod fails due to transient issues and since there are no retries the whole helm install command fails.

While retrying the helm install command works most of the time, such sensitivity to individual resource failures results in overall higher chance of failure at installation time.

**Comment by petewall** [comment]
This will not be an issue in the upcoming 2.0 release.
