### ISSUE TITLE
chart version 1.4.3 contains a breaking change

### ISSUE THREAD

**Issue by morremeyer** [grafana/k8s-monitoring-helm#676]
Chart version 1.4.3 contains a breaking change by introducing the usage of structured metadata. 

This change was introduced with https://github.com/grafana/k8s-monitoring-helm/commit/e2e243d4e7ff7f5d9c032891c918f7c0ba12f5b2 and requires loki to have `allow_structured_metadata` to be explicitly set to `true`.

If this is not done prior to rolling out version 1.4.3, all log write requests to loki will fail with an HTTP 400 error as follows:

> stream includes structured metadata, but this feature is disallowed. Please see `limits_config.structured_metadata` or contact your Loki administrator

I am opening this issue for two reasons:

1. Here's some documentation for anybody affected by the same issue, it took me a moment to find 
2. A small request: Could breaking changes be versioned as such in the future, please?

**Comment by petewall** [comment]
Thanks for catching this. I'll make a fix to make it not a breaking change.

**Comment by morremeyer** [comment]
We also noticed that the `pod` label is missing when upgrading to 1.4.3 and 1.4.4, which I think you already address in #677 by setting it to be off by default and mentioning it.

I assume the idea is to turn structured metadata on by default **and** add the pod label with 2.0.0?

In the meantime, we'll downgrade to 1.4.2 and wait for the release containing #677.

**Comment by petewall** [comment]
Just dropped 1.4.5. Can you try that out? It should stop using structured metadata and keep `pod` as a loki label

**Comment by morremeyer** [comment]
We just upgraded to 1.4.6, I can confirm that the fix in 1.4.5 works as desired.

Thank you for the work and the quick turnaround!
