### ISSUE TITLE
Add additional headers to remote write requests

### ISSUE THREAD

**Issue by snowzach** [grafana/k8s-monitoring-helm#702]
I need to add additional headers to the remote write calls. I don't see any obvious way to do that in this chart. I would be open to trying to do a PR for it but would like a recommended way to specify it and implement it in the values file before I try.

**Comment by petewall** [comment]
I was just about to add this! Let me work on the PR and I'll add you to review.

**Comment by snowzach** [comment]
Yay! FWIW, it would be really great if it were possible to specify the values or via a secret... ie 
```
headers = {
          "X-Scope-OrgID" = nonsensitive(remote.kubernetes.secret.metrics_service.data["tenantId"]),
          "someKey" = remote.kubernetes.secret.metrics_service.data["someSecretKeyValue"],
   }
```

**Comment by snowzach** [comment]
@petewall we're missing an equals sign here: https://github.com/grafana/k8s-monitoring-helm/blob/bdc62b6f875c08dc851c86b826e63dd0432a0f84/charts/k8s-monitoring/templates/alloy_config/_logs_service_loki.alloy.txt#L9

I tried to open a PR but I'm not on Mac and things weren't really working..

**Comment by petewall** [comment]
Thanks! Fixed in main.
