### ISSUE TITLE
Make truncate_frequency, min_keepalive_time, max_keepalive_time configurable

### ISSUE THREAD

**Issue by Raboo** [grafana/k8s-monitoring-helm#733]
Hi,

I have a feature request.

I would love if the following values were configurable.

```hcl
prometheus.remote_write "metrics_service" {
  wal {
    truncate_frequency = "2h"
    min_keepalive_time = "5m"
    max_keepalive_time = "8h"
  }
}
```

This in order to be able better control memory consumption.

**Comment by petewall** [comment]
You can set those settings:
https://github.com/grafana/k8s-monitoring-helm/blob/main/charts/k8s-monitoring/values.yaml#L227-L239

**Comment by Raboo** [comment]
Don't I feel stupid. Can't believe I missed that... 🤦

**Comment by petewall** [comment]
No worries! Glad it was an easy one!
