### ISSUE TITLE
Alloy 1.5.3 Bug - alloy-logs daemonset stuck in 'ContainerCreating' as ConfigMap does not exist

### ISSUE THREAD

**Issue by jark-AB** [grafana/k8s-monitoring-helm#748]
In the default [values.yaml](https://github.com/grafana/k8s-monitoring-helm/blob/main/charts/k8s-monitoring/values.yaml#L1534-L1543), setting the following enables the alloy-logs child chart to add a `alloy-logs` daemonset.

```
logs:
  enabled: true
  pod_logs:
    enabled: false
  cluster_events:
    enabled: true
```

The expected behavior is when setting `logs enabled: true`, we do not expect the child chart to render the `alloy-logs` daemonset. The Alloy logs daemonset is referring to a ConfigMap that doesn't exist as the parent chart doesn't contain the ConfigMap.

This occurs in the latest k8s-monitoring `1.5.3`, we upgraded from `1.4.1`. 

Additional Error Message:
```
  Warning  FailedMount  4s (x1918 over 2d16h)  kubelet  MountVolume.SetUp failed for volume "config" : configmap "grafana-cloud-alloy-logs" not found
```

REF:
https://github.com/grafana/k8s-monitoring-helm/blob/main/charts/k8s-monitoring/templates/alloy-logs-config.yaml#L1
https://github.com/grafana/alloy/blob/main/operations/helm/charts/alloy/templates/controllers/daemonset.yaml

**Comment by petewall** [comment]
There has always been a bit of a tangle between `.Values.logs.enabled` and cluster events, pod logs, and other "log" based things. I'll try to improve things.

**Comment by jark-AB** [comment]
Thanks for the quick fix @petewall ! What is the release cadence to have this integrated to the chart? Would a release be cut this week?

**Comment by petewall** [comment]
Release cadence is "as needed", but higher-priority bugfixes will make things happen sooner than later. I'm creating 1.5.4 right now.
