### ISSUE TITLE
Add "extraObjects:"  to the helm chart of k8s-monitoring for Grafana Alloy

### ISSUE THREAD

**Issue by Federico-Baldan** [grafana/k8s-monitoring-helm#770]
Hi, I wanted to ask if it would be possible to add the `"extraObjects:" `section in the values.yaml of the helm chart for k8s-monitoring.
This section was available in the "v1" chart but is missing from the new version.
Could you please consider including it?
Thank you very much in advance

**Comment by petewall** [comment]
Good call. I'll make sure it's brought over.
