### ISSUE TITLE
What is difference between k8s-monitoring and k8s-monitoring-v1 charts?

### ISSUE THREAD

**Issue by weteamsteve** [grafana/k8s-monitoring-helm#777]
Hey all,

I had a question

What is difference between [`k8s-monitoring`](https://github.com/grafana/k8s-monitoring-helm/blob/main/charts/k8s-monitoring/Chart.yaml) and [`k8s-monitoring-v1`](https://github.com/grafana/k8s-monitoring-helm/tree/main/charts/k8s-monitoring-v1) charts?

Is k8s-monitoring-v1 being deprecated? How long will k8s-monitoring be in alpha? What is the long term outlook for both of these?

**Comment by petewall** [comment]
k8s-monitoring-v1 is the current "k8s-monitoring Helm chart". It is currently at version 1.5.6 and I don't have any immediate plans to deprecate it.
k8s-monitoring is where development of version 2.0 is occurring. There isn't a release yet.

Major feature development is focussed on 2.0, while 1.x will get patches and bugfixes for a while. Again, no announcement today of when 1.x will stop getting updates.
