### ISSUE TITLE
Add bearer_token auth for loki service

### ISSUE THREAD

**Issue by MairaTariq16** [grafana/k8s-monitoring-helm#808]
k8s-monitoring helm chart should expose `bearer_token` and `bearer_token_file` configuration for `loki.write` component. Similar implementation has been recently added for the `prometheus.remote_write` component in #615.

**Comment by MairaTariq16** [comment]
I see that the option is available in the [v2 chart](https://github.com/grafana/k8s-monitoring-helm/blob/main/charts/k8s-monitoring/docs/destinations/loki.md) but it is not released yet. Is v1 no longer maintained? When is v2 expected to be released?

**Comment by petewall** [comment]
There is no reason the v1 chart cannot have bearer token auth for Loki. I'll try and make a change to include it.

**Comment by petewall** [comment]
The V1 change will support bearer token files, but you'll need to ensure that the bearer token is mounted to the Alloy instances.
V2 provides support for bearer token files through the `auth.bearerTokenFrom` field, where you can use:
```
destinations:
- ...
  auth
    bearerTokenFrom: local.file.my_bearer_token.content
alloy-metrics:
  extraConfig: |
    local.file "my_bearer_token" {
      filename = <path to bearer token>
      is_secret = true
    }
```
