### ISSUE TITLE
Disabling node_exporter but node_exporter_build_info continues to send

### ISSUE THREAD

**Issue by Jwalker107** [grafana/k8s-monitoring-helm#822]
Please forgive me if I'm missing something obvious.  I'm fairly new to Helm charts and I'm trying to understand some interdependencies between charts here.

I'm using a Grafana Cloud instance and starting with the configuration created by the Kubernetes datasource integration there. I quickly overran the Metrics collection per user ( err-mimir-max-series-per-user ) and I am turning the knobs to understand each collection source.

**Expectation:**
With the following as part of the configuration file, I expect that all of the node-exporter features would be disabled and no node-exporter metrics would be sent:

```
metrics:
  enabled: true

  node-exporter:
    enabled: false

prometheus-node-exporter:
  enabled: false
```

**Actual:**
When I redeploy this chart, I see that many node-exporter metrics stop sending.  For example `container_cpu_usage_seconds_total` metrics stop reporting as shown in `Home -> Explore -> Metrics -> container_cpu_usage_seconds_total`

However in the Kubernetes Dashboard's `Configuration -> Metrics` tab, the 'Node Exporter' metric continues to display a green checkbox, and checking again in the Explorer-> Metrics I can see that 'node_exporter_build_info' continues to report.

I'm trying to understand why node_exporter_build_info appears to be continue reporting, whether I have actually disabled node_exporter metrics or have failed to select a correct metric to check, and whether there is some other area I should be disabling.

I thank you for you consideration and for helping a newbie on this.

**Comment by petewall** [comment]
I think I found that an additional node_exporter_build_info is being sent by the chart's internal telemetry reporting. I'll fix that.

**Comment by Jwalker107** [comment]
Thanks very much!  I found it to be a bit confusing.
