### ISSUE TITLE
2.0 customize import.git location in alloy configuration

### ISSUE THREAD

**Issue by lasher23** [grafana/k8s-monitoring-helm#839]
**Description**
I checked out the v2 Version of the chart and i liked it quite alot, so i gave it a try in a testing environment. Than i hit the error that Alloy can not import the git configurations, because my cluster has no access to GitHub. For example "import.git "kube_state_metrics"".

**Problem**
Alloy Configuration import.git modules hardcoded to GitHub

**Possible Solution**
Either allow to configure another Repository or provide a way to confiugre the necessary declarations. You might also come up with something even better.

I know the V2 is not production ready, would just be awesome if this would be included in V2

**Comment by petewall** [comment]
Yes! Thank you for highlighting this. I was actually thinking yesterday while away from my desk "I gotta put some configuration around the alloy module options". I'll use this issue to track the changes.

**Comment by lasher23** [comment]
Thats some crazy fast work . Thanks alot, will give it a try as soon as possible.

Love the direction this chart is heading 🥳

Will this be in a RC soon?

**Comment by petewall** [comment]
https://github.com/grafana/k8s-monitoring-helm/releases/tag/v2.0.0-rc.2 is out now!
