### ISSUE TITLE
Add scrape intervals to each metric?

### ISSUE THREAD

**Issue by petewall** [grafana/k8s-monitoring-helm#84]
I've heard that there was confusion over the default scrape interval being used when scraping metrics.

The default is `60s`, which is set in [prometheus.scrape](https://grafana.com/docs/agent/latest/flow/reference/components/prometheus.scrape/#arguments). However, a user not familiar with flow might not know that is the default. They wouldn't necessarily know to dig down into agent documentation.

If we set:
```
node-exporter:
  scrapeInterval: 60s
```

And use that in the generated config, it would make it explicit.

**Comment by petewall** [comment]
Question: Is this useful, or adding config that will likely never be changed?

**Comment by marahanus** [comment]
Hello @petewall,
would be nice to have posibility to configure scrape interval for all "prometheus.scrape" in configuration.

In my case: I have been using Grafana Cloud Pro and would like to decrease DPM. I have been scraping own app's metrics in higher resolution so I need to set lower resolution elsewhere.
