### ISSUE TITLE
Bump opencost chart to 1.18.1

### ISSUE THREAD

**Issue by skl** [grafana/k8s-monitoring-helm#90]
See CNCF slack announcement [here](https://cloud-native.slack.com/archives/C03D56FPD4G/p1692819735494159).

Also watch out for:

- https://github.com/opencost/opencost-helm-chart/pull/106

How does one go about bumping dependencies?

**Comment by petewall** [comment]
Bumping dependencies (maybe this needs to be a doc):
1. Update the dependency's version in Chart.yaml
2. Run `helm dependency update`
3. Run `helm-docs`
4. Bump the chart version.
5. `make regenerate-example-outputs` and take a moment to inspect the generated output for anything that might cause trouble. Likely wont happen for bugfix releases, though.

That *should* be all you need for dependency updates.
