### ISSUE TITLE
Adding extraLabels to OTLP destination in k8s-monitoring-helm V2 not working.

### ISSUE THREAD

**Issue by cxk314** [grafana/k8s-monitoring-helm#946]
Hi,
I am trying to add static extra labels to all metrics sent with OTLP monitoring but it doesn't appear to be working. According to the [Migration guide](https://github.com/grafana/k8s-monitoring-helm/blob/main/charts/k8s-monitoring/docs/Migration.md#steps-to-take) `externalLabels` --> `extraLabels` but this config doesn't appear to be working:

```
cluster:
  name: my-cluster

destinations:
  - name: otlp
    type: otlp
    url: https://np-grpc.np-shared-aks.com
    extraLabels:  
      MY_LABEL: my-label
```
The generated config map for Alloy Receiver has only this:
```
      otelcol.processor.transform "otlp" {
        error_mode = "ignore"
        metric_statements {
          context = "resource"
          statements = [
            "set(attributes[\"cluster\"], \"my-cluster\") where attributes[\"cluster\"] == nil",
            "set(attributes[\"k8s.cluster.name\"], \"my-cluster\") where attributes[\"k8s.cluster.name\"] == nil",
          ]
        }
        log_statements {
          context = "resource"
          statements = [
            "set(attributes[\"cluster\"], \"my-cluster\") where attributes[\"cluster\"] == nil",
            "set(attributes[\"k8s.cluster.name\"], \"my-cluster\") where attributes[\"k8s.cluster.name\"] == nil",
          ]
        }
        trace_statements {
          context = "resource"
          statements = [
            "set(attributes[\"cluster\"], \"my-cluster\") where attributes[\"cluster\"] == nil",
            "set(attributes[\"k8s.cluster.name\"], \"my-cluster\") where attributes[\"k8s.cluster.name\"] == nil",
          ]
        }

        output {
          metrics = [otelcol.exporter.otlp.otlp.input]
          logs = [otelcol.exporter.otlp.otlp.input]
          traces = [otelcol.exporter.otlp.otlp.input]
        }
      }
```
How to add extra static labels to everything that is sent with k8s-monitoring-helm?

**Comment by petewall** [comment]
otlp destinations don't have an `extraLabels` section, but you can now specify actions in an attributes processor or statements in a transform processor.

**Comment by cxk314** [comment]
How would I do that globally? Is it possible Can you provide an example of it?

**Comment by cxk314** [comment]
It doesn't appear to be working. Cannot find that label added to telemetry. I also don't see anywhere in the config maps this processor added, as if it was ignored.

**Comment by cxk314** [comment]
It appears 2.0.0-rc.6 added support for processors in otlp destination. Suggested solution working now.
