### ISSUE TITLE
Agent isn't setting __replica__ label by default

### ISSUE THREAD

**Issue by rknightion** [grafana/k8s-monitoring-helm#95]
Having recently switched to this helm chart as we're building out a Mimir setup, I think I've run into an issue.

When setting the agent statefulset to run multiple replicas for HA mode, I get lots of rejected duplicate samples in the logs and the Mimir HA dashboard shows it's not recognised as a HA agent setup.

I believe Mimir by default expects the __replica__ label to be set on all incoming metrics but that this isn't being set by default in this chart. 

I did try setting `__replica__: ${POD_NAME}` in the externalLabels section of the chart, but this didn't seem to register correctly (it ended up sending ${POD_NAME} as the replica name which of course didn't work). 

Am I missing something in the chart values for this to be setup correctly as I think it should be the default for the agent when running it in HA mode?

**Comment by petewall** [comment]
Hi Rob!
https://github.com/grafana/k8s-monitoring-helm/releases/tag/v0.1.15 included some fixes to the Agent clustering behavior. The statefulset that gathers metrics should properly distribute scrape jobs across the different instances, resulting in less duplicate metrics being sent to Mimir. Try with the latest release and see if you're still seeing issues.

**Comment by rknightion** [comment]
Rolling that out and things seem a lot better!

Also very happy to see the HA side being handled by the agent itself rather than the HA reconciler needed in Mimir (that initially confused me not seeing the agent show up in the HA list on the Ingester). Great stuff!
