### ISSUE TITLE
Add opencost to 2.0 chart

### ISSUE THREAD

**Issue by eliihen** [grafana/k8s-monitoring-helm#971]
Hi Pete, love your work!

The v2 k8s-monitoring chart currently does not include opencost like v1, so I thought why not create an issue to track the cost monitoring aspect

**Comment by petewall** [comment]
Yep! Just as @william413215 said, OpenCost is in the v2 chart, just inside the cluster metrics feature!

**Comment by eliihen** [comment]
My bad, thanks! 🚀

I found no mention of cost or finops on the main k8s-monitoring README or in the [Features](https://github.com/grafana/k8s-monitoring-helm/blob/main/charts/k8s-monitoring/docs/Features.md) document, that's how I reached that conclusion that it was still in the works 🙂
