### ISSUE TITLE
Incorrect logs parsing

### ISSUE THREAD

**Issue by DawPawel** [grafana/k8s-monitoring-helm#98]
Heyo,

I've been using v0.0.15 of this chart and everything was working ok - both logs and metrics.
After upgrade (don't remember exact version (>v0.1.x) I started receiving strange logs.

Logs look now like that:
```
<time> <output stream> F <log_line>
2023-08-29T19:19:00.559181246Z stdout F {"jsonLogKey": "value"}
```
which breaks json parsing in Loki.

Tested with the latest version (0.1.15) and problem still exists.

**Comment by petewall** [comment]
Glad things are working for you!

We're talking about the default parsing format in #100 . I'm going to close this issue in favor of that one.
