### ISSUE TITLE
v2.0.0-rc.7 charts/feature-integrations/integrations/etcd-values.yaml etcd labelSelector

### ISSUE THREAD

**Issue by mvink-guida** [grafana/k8s-monitoring-helm#987]
please make the ETCD label configurable, currently there is a mandatory label `app.kubernetes.io/component: etcd `set due to the merge.

![Image](https://github.com/user-attachments/assets/ba6805df-0051-4b4b-9a0f-68b61cf1c8b6)

https://github.com/grafana/k8s-monitoring-helm/blob/v2.0.0-rc.7/charts/feature-integrations/integrations/etcd-values.yaml#L16

proposed

```yaml
# -- Discover etcd instances based on label selectors.
# @section -- Discovery Settings
labelSelectors: {}
```

**Comment by petewall** [comment]
Fair point. The real issue is that Helm has a bug that prevents you from `null`'ing a value reliably.

**Comment by petewall** [comment]
I've got a PR in the works that will fix this. It'll now set `app.kubernetes.io/component: <name>`, but you can set it to null now, and specify your own label.
