### ISSUE TITLE
 HTTP status 404 Not Found: 404 page not found

### ISSUE THREAD

**Issue by thisurawijesekera** [grafana/k8s-monitoring-helm#99]
Hi 

I am getting 400 error for my pushgateway from the grafana agent. But when I write sample data through a curl command it worked  

`ts=2023-08-30T19:16:22.239618449Z component=prometheus.remote_write.grafana_cloud_prometheus subcomponent=rw level=error remote_name=8117c6 url=https://XXXXXX:XXXXXXX%40123@XXXXXXXXXX.XXXXXXXX.XXXXXXXXXXXX.io/metrics/job/some_job msg="non-recoverable error" count=564 exemplarCount=0 err="server returned HTTP status 400 Bad Request: snappy: corrupt input"`

**Comment by petewall** [comment]
I'm going to close this issue. If you have further questions, please let me know!
